<?php
use SeuDo\Main;
$document = $this->document();
$publicPath = Main::getHomeUrl();
$document->title = t("Đăng ký");
$cssPath = $publicPath . 'assets/css/';
$jsPath = $publicPath . 'assets/js/process/';
$jsPathFront = $publicPath . 'assets/js/';
$states = @$states;
?>
<section class="page-register">
    <nav class="container" >
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
                <div class="seu-module">
                    <div class="module-inner">
                        <div class="module-title">
                            <p class="title"><span class="title-page">Đăng ký</span><span class="pull-right">Bạn đã có tài khoản? <a href="<?php echo Main::getHomeRouter()->createUrl('login/login');;?>">Đăng nhập tại đây</a></span></p>
                        </div>
                        <form method="" id="frm-register">
                        <div class="module-ct">
                            <div class="module-ct-item">
                                <div class="left-ct">
                                    <span class="normal-blod">Tài khoản <span class="red-normal">*</span> :</span>
                                </div>
                                <div class="right-ct pull-right">
                                    <input name="input[username]" id="username" class="form-control form-myinput" type="text" placeholder="Tài khoản" onblur="blurUsername('frm-register');">
                                    <p class="red-normal" id="error-username"></p>
                                    <p class="normal">Sử dụng các ký tự latin (a-z) và ký tự gạch dưới. Từ 3 đến 15 ký tự</p>
                                </div>
                            </div>
                            <div class="module-ct-item">
                                <div class="left-ct">
                                    <span class="normal-blod">Email <span class="red-normal">*</span> :</span>
                                </div>
                                <div class="right-ct pull-right">
                                    <input name="input[email]" id="email" class="form-control form-myinput" type="text" placeholder="Email" >
                                    <p class="red-normal" id="error-email"></p>
                                    <p class="normal">Seudo sẽ gửi các thông báo tới email này. Vui lòng sử dụng email tồn tại.</p>
                                </div>
                            </div>
                            <div class="module-ct-item password">
                                <div class="left-ct">
                                    <span class="normal-blod">Mật khẩu <span class="red-normal">*</span> :</span>
                                </div>
                                <div class="right-ct pull-right">

                                    <input name="input[password]" id="password" data-password="" class="form-control form-myinput strength_password" type="password" placeholder="Mật khẩu (tối thiểu 6 ký tự)" >
                                    <p class="red-normal" id="error-password"></p>
                                    <span class="password_strength"></span><br>

                                    <input name="input[repassword]" id="repassword" class="form-control form-myinput" type="password" placeholder="Nhập lại mật khẩu" >
                                    <p class="red-normal _repassword" id="error-repassword"></p>
                                </div>

                            </div>
                            <hr>
                            <div class="module-ct-item">
                                <div class="left-ct">
                                    <span class="normal-blod">Họ & Tên <span class="red-normal">*</span> :</span>
                                </div>
                                <div class="right-ct name pull-right">
                                    <input name="input[last_name]" id="first_name" class="form-control form-myinput" type="text" placeholder="Họ" >
                                    <input name="input[first_name]" id="last_name" class="form-control form-myinput pull-right" type="text" placeholder="Tên" >
                                    <p class="red-normal" id="error-fullname"></p>
                                </div>

                            </div>
                            <div class="module-ct-item made">
                                <div class="left-ct">
                                    <span class="normal-blod">Giới tính <span class="red-normal">*</span> :</span>
                                </div>
                                <div class="right-ct pull-right">
                                        <span class="radio">
                                          <label>
                                              <input type="radio" checked="" value="1" id="gender" name="input[gender]">
                                              Nam
                                          </label>
                                        </span>
                                        <span class="radio">
                                          <label>
                                              <input type="radio" checked="" value="0" id="gender" name="input[gender]">
                                              Nữ
                                          </label>
                                        </span>
                                        <span class="radio">
                                          <label>
                                              <input type="radio" checked="" value="2" id="gender" name="input[gender]">
                                              Khác
                                          </label>
                                        </span>
                                </div>
                            </div>
                            <div class="module-ct-item select">
                                <div class="left-ct">
                                    <span class="normal-blod">Địa chỉ:</span>
                                </div>
                                <div class="right-ct pull-right ">
                                    <select class="_ajaxState selectCountry" id="tt_id" name="input[tt_id]">
                                        <option class="_selectState" value="-1">Tỉnh/Thành phố</option>
                                        <?php
                                        foreach($states as $state){
                                        ?>
                                        <option class="_selectState" value="<?php echo $state->getId();?>"><?php echo $state->getLabel();?></option>
                                        <?php
                                        }
                                        ?>
                                    </select>
                                    <select class="pull-right _afterDistrict selectCountry" id=""  disabled="disabled" >
                                        <option value="-1" class="">Quận/Huyện</option>
                                    </select>
                                    <select class="pull-right _ajaxDistrict selectCountry hidden" id="qh_id" name="input[qh_id]">
                                        <option value="-1" class="">Quận/Huyện</option>
                                    </select>
                                    <textarea name="input[detail_address]" id="detail_address" class="form-control form-mytextarea" placeholder="Số nhà" rows="3"></textarea>
                                    <p class="red-normal" id="error-address"></p>
                                </div>
                            </div>
                            <div class="module-ct-item">
                                <div class="left-ct">
                                    <span class="normal-blod">Yahoo ID:</span>
                                </div>
                                <div class="right-ct pull-right">
                                    <input name="input[yahoo]" id="exampleInput" class="form-control form-myinput" type="text" placeholder="Nhập tài khoản Yahoo của bạn ..." >
                                </div>
                            </div>
                            <div class="module-ct-item">
                                <div class="left-ct">
                                    <span class="normal-blod">Skyper:</span>
                                </div>
                                <div class="right-ct pull-right">
                                    <input name="input[skype]" id="exampleInput" class="form-control form-myinput" type="text" placeholder="Nhập tài khoản Skyper của bạn ..." >
                                </div>
                            </div>
                            <p class="normal">Với việc đăng ký tài khoản, tôi đã đồng ý với các điều khoản của SeuDo.vn</p>
                            <p class="submit"><button class="btn btn-blue _btnSubmit" type="submit">Đăng ký</button></p>
                            <p class="submit"><button class="btn btn-blue btnShow _hide" type="submit">Vui lòng chờ trong giây lát...</button></p>
                        </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </nav>
</section>

