<?php
use SeuDo\Main;
$document = $this->document();
$publicPath = Main::getHomeUrl();
$document->title = t("Kích hoạt tài khoản thành công!");
$cssPath = $publicPath . 'assets/css/';
$imgPath = $publicPath.'assets/images';
$jsPathFront = $publicPath . 'assets/js/';
?>

<section class="page-register editavatar">
    <nav class="container" >
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                            <div class="alert icon-alert-success col-md-12">
                                <h4>THÀNH CÔNG!</h4>
                                <p>Tài khoản của bạn đã được kích hoạt trên hệ thống Sếu đỏ.</p>
                            </div>
            </div>
            <!--        </div>-->
    </nav>

</section>
