<?php
use Flywheel\View\Render;
/** @var Render $this */
/** @var \Backend\Controller\Order\Detail $controller */
/** @var \Order $order */

$document = $this->document();

$document->addCss('css/order.css');
$document->addCss('css/style-chitietdonhang.css');
$document->addCss('css/extend/quyen_order_detail.css');
$document->addJs('js/handlebars-v1.3.0.js', 'TOP');
//$document->addJs('js/process/order.js');
$document->addJs('js/autoNumeric.js');
$document->addJs('js/process/order_detail.js');
$document->addJs('js/seudo-backendv1.js');
$document->addJs('js/jqueryui.js');

$document->addJsVar('get_order_items_url', $this->createUrl('order/detail/get_items'));
$document->addJsVar('link_add_order_comment', $this->createUrl('order/order_comment/add_message'));
$document->addJsVar("linkAddComplaintSeller", $this->createUrl('ComplaintSeller/init/addcomplaintseller'));
$document->addJsVar("linkUpdateStatusSuccessComplaintSeller", $this->createUrl('ComplaintSeller/init/updatestatussuccess'));
$document->addJsVar("linkUpdateStatusFailureComplaintSeller", $this->createUrl('ComplaintSeller/init/updatestatusfailure'));
$document->addJsVar('add_fee_wood_crating', $this->createUrl('orderCommon/updateFeeWoodCrating'));

$document->addJsVar("linkGetListComplaintSellers", $this->createUrl('ComplaintSeller/managerment/GetListComplaintSellers'));
$document->addJsVar('linkGetListComplaint', $this->createUrl('Complaint/Managerment/GetGirdComplaints'));
$document->addJsVar('linkGetListTransactionOrder', $this->createUrl('order/detail/GetListTransactionOrder'));
$document->addJsVar('linkGetListFreeOrder', $this->createUrl('order/detail/GetListFreeOrder'));

$document->addJsCode('
    var chat_row_template = Handlebars.compile($("#_order_chat_row_template").html());
    var order_item_comment_template = Handlebars.compile($("#_order_item_comment").html());
    var item_order_item_comment_template = Handlebars.compile($("#_item_order_item_comment").html());

    Handlebars.registerPartial("list_item_comments", $("#_item_order_item_comment").html());', 'BOTTOM', 'standard'
);

$this->document()->addJsVar("linkAddOrderComment",$this->createUrl('Order/OrderComment/AddMessage'));
$this->document()->addJsVar("linkAddOrderItemComment", $this->createUrl('Order/OrderItemComment/AddMessage'));
$this->document()->addJsVar("linkMoreOrderItemComment", $this->createUrl('Order/OrderItemComment/ListMoreComments'));
//$this->document()->addJsVar("linkLoadBoxChat", $this->createUrl('Order/OrderComment/LoadBoxChat'));
$this->document()->addJsVar("linkListOrderComments", $this->createUrl('Order/OrderComment/ListOrderComments'));
$this->document()->addJsVar("linkGetAllOrderItemComments", $this->createUrl('Order/OrderItemComment/GetAllOrderItemComments'));

?>
<style>
    #_services_fee ._fee .item-bottom {
        padding-bottom: 20px;
    }
    #_services_fee ._fee .item-bottom .font-gray-dark {
        font-weight: bold;
    }
    #_services_fee ._fee ._services-fee {
        margin-left: 10px;
        font-size: 12px;
        font-weight: normal !important;
    }
    #_services_fee ._fee ._services-fee .font-gray-dark {
        font-size: 12px;
        font-weight: normal !important;
    }
</style>

<!-- dau's -->
<script id="_order_item_comment" type="text/x-handlebars-template">
    {{#each info}}
    {{> list_item_comments}}
    {{/each}}
</script>
<!-- dau's -->
<script id="_item_order_item_comment" type="text/x-handlebars-template">
    <div class="_content_chat_item_view"><span class="normal-blod">{{username}}</span> {{{message}}}</div>
</script>

<script id="_order-detail-page" type="text/x-handlebars-template">
<!-- HEADER -->
<div id="page-title" class="seu-main-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-7">
                <h3 class="main-header-title uppercase">{{code}}
                    - {{order_status status}}
                </h3>
                {{#if need_checking}}
                <span class="label primary-bg">Có kiểm hàng</span>
                    {{#if is_checking_status_checked}}
                        - <span class="label primary-bg">Đã kiểm</span>
                    {{/if}}
                    {{#if is_checking_status_not_yet_checked}}
                        - <span class="label primary-bg">Chưa kiểm</span>
                    {{/if}}
                {{else}}
                - <span class="label primary-bg">Không kiểm</span>
                {{/if}}
                {{#if check_wood_crating}}
                - <span class="label bg-green">Có đóng gỗ</span>
                {{/if}}
                {{#if check_fragile}}
                - <span class="label bg-orange">Dễ vỡ</span>
                {{/if}}
                {{#if is_cpn}}
                <span class="label primary-bg">Có CPN</span>
                {{/if}}

            </div>
            <div class="col-lg-5 col-md-5 col-xs-5">
                <p class="font-gray uppercase">
                    Người bán:
                </p>
                <a target="_blank" rel="nofollow" href="http://{{seller_name}}.{{seller_home_land}}.com"><img src="{{seller_favicon_site}}"></a>
                {{seller_name}}
            </div>
        </div>


    </div>
</div>
<!--/header -->

<!-- ORDER INFO -->
<div class="seu-page-content item-detail no-header">
<div class="container">
<div class="row">
<div class="tab-content main-chat-v2">
<div class="main-content">

<div class="module-title _fee">
    <div class="module-float">
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Tạo đơn</p>
            <p>{{date created_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Đặt cọc</p>
            <p>{{date deposit_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Đã Pai</p>
            <p>{{date paid_staff_assigned_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Đàm phán</p>
            <p>{{date negotiated_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Mua hàng</p>
            <p>{{date bought_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Người bán giao</p>
            <p>{{date seller_delivered_time}}</p>
        </div>

    </div>

    <div class="module-float">

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Nhận hàng người bán</p>
            <p>{{date received_from_seller_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Kiểm hàng</p>
            <p>{{date checked_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Chờ giao</p>
            <p>{{date waiting_delivery_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Y/c giao</p>
            <p>{{date confirm_delivery_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Giao hàng</p>
            <p>{{date delivered_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Nhận hàng</p>
            <p>{{date received_time}}</p>
        </div>

    </div>

    <div class="module-float">
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Hết hàng</p>
            <p>{{date out_of_stock_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Hủy</p>
            <p>{{date cancelled_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Khách thanh toán</p>
            <p>{{date real_payment_last_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Nhập kho</p>
            <p>{{date warehouse_in_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Xuất kho</p>
            <p>{{date warehouse_out_time}}</p>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Mã vạch ( <span class="font-small">Id: {{id}}</span> )</p>
            <p>S/{{id}}</p>
        </div>

    </div>

    <div class="module-float">
        <div class="col-lg-2 col-md-2 col-sm-2">
            <p class="font-gray uppercase">Vận chuyển</p>
            <p>{{date transporting_time}}</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2">
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2">
        </div>

    </div>

</div>

<div class="border-header-list">
    <div class="border"></div>
</div>

<div class="module-title">
    <div class="item-title title">
        <div class="col-lg-3 col-md-3">
            {{#if buyer}}
            <div class="left-title font-gray-dark">
                KHÁCH HÀNG
            </div>
            <div class="right-title">
                <div class="position-avatar">
                    <a href="{{buyer.detail_link}}" target="_blank"><img class="img-circle" alt="" src="{{buyer.avatar}}"  width="32" height="32"></a>
                </div>
                <p class="normal">
                    <a href="{{buyer.detail_link}}" target="_blank"><strong>{{buyer.last_name}} {{buyer.first_name}}</strong></a> ({{buyer.code}})
                </p>
                <p class="normal font-user">@{{buyer.username}}</p>
            </div>
            {{else}}
            <p class="font-gray"><?php t('Không có quyền xem'); ?></p>
            {{/if}}
        </div>

        <div class="col-lg-8 col-md-8 col-xs-8">
            <div class="left-title font-gray-dark">
                Địa chỉ
            </div>
            {{#if address}}
                <div class="map-add-detail">
                    <span class="icon-map">
                        <i class="glyph-icon icon-map-marker"></i>
                    </span>

                    {{#if address.error}}
                        <p class="normal">{{address.error}}</p>
                    {{else}}
                        <p class="normal"><strong>{{address.reciver_name}}</strong> {{address.detail}}, {{address.district.label}}, {{address.province.label}} {{#if address.reciver_phone}} / {{address.reciver_phone}}{{/if}}</p>
                        {{#if address.note}}
                            <p class="font-gray-dark">{{address.note}}</p>
                        {{/if}}
                    {{/if}}
                </div>
            {{else}}
                <p class="font-gray-dark">Không có quyền xem</p>
            {{/if}}
        </div>

    </div>

    <div class="item-title">
        <div class="col-lg-3 col-md-3">
            <p class="left-title font-gray">Người nhận</p>
            {{name_recipient_origin}}
        </div>

        <div class="col-lg-3 col-md-3">
            <p class="left-title font-gray">User mua hàng</p>
            {{account_purchase_origin}}
        </div>

        <div class="col-lg-3 col-md-3">
            <p class="left-title font-gray">Kho hiện tại / Kho đích</p>
            {{#if current_warehouse}}
            {{current_warehouse}}
            {{else}}
            ~~
            {{/if}}

            {{#if destination_warehouse}}
            / {{destination_warehouse}}
            {{else}}
            / ~~
            {{/if}}
        </div>

        <div class="col-lg-3 col-md-3">
            <p class="left-title font-gray">Trạng thái kho</p>
            {{warehouse_status}}
            <br />
            <strong>
                {{#if show_warehouse_in_time}}
                    {{date warehouse_in_time}}
                {{/if}}
                {{#if show_warehouse_out_time}}
                    {{date warehouse_out_time}}
                {{/if}}
            </strong>
        </div>
    </div>

    <div class="item-title">


        <div class="col-lg-3 col-md-3">
            <div class="left-title font-gray">Vận đơn</div>
            {{#each packages}}
            <p class="normal">
                {{freight_bill}}
            </p>
            {{/each}}
        </div>

        <div class="col-lg-3 col-md-3">
            <div class="left-title font-gray">Mã đơn hàng gốc</div>
            <p class="normal">
                {{invoice}}
            </p>
        </div>

        <div class="col-lg-3 col-md-3">
            <div class="left-title font-gray">Hóa đơn Alipay</div>
            <p class="normal">
                {{alipay}}
            </p>
        </div>

        <div class="col-lg-3 col-md-3">
            <p class="left-title font-gray">Nhân viên</p>
            {{#if teller}}
            <a class="user-img-tool" title="" rel="tooltiptop" href="{{teller.detail_link}}" data-original-title="Mua hàng <br>@{{teller.username}}" target="_blank">
                <img class="img-circle" alt="" src="{{teller.avatar}}" width="24" height="24">
            </a>
            {{/if}}

            {{#if payment}}
            <a class="user-img-tool" title="" rel="tooltiptop" href="{{payment.detail_link}}" data-original-title="Thanh toán <br>@{{payment.username}}" target="_blank">
                <img class="img-circle" alt="" src="{{payment.avatar}}"  width="24" height="24">
            </a>
            {{/if}}

            {{#if user_checked}}
            <a class="user-img-tool" title="" rel="tooltiptop" href="{{user_checked.detail_link}}" data-original-title="Kiểm <br>@{{user_checked.username}}" target="_blank">
                <img class="img-circle" alt="" src="{{user_checked.avatar}}"  width="24" height="24">
            </a>
            {{/if}}

            {{#if delivery_staff}}
            <a class="user-img-tool" title="" rel="tooltiptop" href="{{delivery_staff.detail_link}}" data-original-title="Nhân viên giao hàng <br>@{{delivery_staff.username}}" target="_blank">
                <img class="img-circle" alt="" src="{{delivery_staff.avatar}}"  width="24" height="24">
            </a>
            {{/if}}

        </div>

    </div>
</div>

<!-- ITEM PLACEHOLDER -->
<div class="list-cart-order" id="_list-item-placeholder">

</div>
<!--\ item placeholder -->

<!--
<div class="row font-gray-dark order-date">
    <div class="col-lg-8 col-md-8 bottom-margin">
        <div class="col-lg-2">Đặt cọc:<br> <strong>{{date deposit_time}}</strong></div>
        <div class="col-lg-2">Pai:<br> <strong>{{date negotiating_time}}</strong></div>
        <div class="col-lg-2">Mua hàng:<br> <strong>{{date bought_time}}</strong></div>
        <div class="col-lg-2">Người bán giao: <strong>{{date seller_delivered_time}}</strong></div>
        <div class="col-lg-2">Nhận hàng CNGZ: <strong>{{date received_from_seller_time}}</strong></div>
    </div>
    <div class="col-lg-8 col-md-8">
        {{#if is_deleted}}
        <div class="col-lg-2">Hết hàng: <strong>{{date out_of_stock_time}}</strong></div>
        <div class="col-lg-2">Hủy: <strong>{{date cancelled_time}}</strong></div>
        {{else}}
        <div class="col-lg-2">Kiểm xong:<br> <strong>{{date checked_time}}</strong></div>
        <div class="col-lg-2">Giao khách: <strong>{{date delivered_time}}</strong></div>
        <div class="col-lg-2">Khách nhận: <strong>{{date delivered_time}}</strong></div>
        {{/if}}
    </div>
</div>
-->





<!-- ORDER BOTTOM -->
<div class="custom-bottom module-title">
<div class="top">
    <div class="row">
        <div class="col-lg-4 col-md-4 check-all">
            <span class="arrow"></span>
            Với những sản phẩm đã chọn
            <a id="_btn_out_of_stock">Hết hàng</a> |
            <a id="_btn_receive_enough">Nhận đủ</a>
        </div>

        <div class="col-lg-2 col-md-2">
            {{#if edit_weight}}
            <div class="form-row">
                <div class="form-input col-lg-12">
                    <div class="input-append-wrapper input-append-right">
                        <a class="input-append primary-bg _change-weight" href="javascript:;">
                            <i class="glyph-icon icon-save"></i>
                        </a>
                        <div class="append-right">
                            <input type="text" placeholder="Trọng lượng" value="{{#if weight}}{{weight}}{{/if}}" name="weight_input" id="_order-weight-input" data-order-id="{{id}}">
                        </div>
                        <div class="dropdow-error">
                            <p class="font-small">Trọng Lượng (gram). Vd: 1,5 kg = 1500 gram</p>
                        </div>
                    </div>
                </div>
            </div>
            {{else}}
            <p class="normal"><strong>{{weight}}</strong> gram</p>
            {{/if}}
        </div>

        <div class="col-lg-6 col-md-6">
            <div class=" text-right">
                <a class="btn medium transparent _print-barcode" href="javascript:javascript:void(0)" title="">
                                                    <span class="button-content uppercase">
                                                    <i class="glyph-icon icon-print"></i>
                                                    In Mã Vạch
                                                    </span>
                </a>
                                            <?php if($controller->isAllowed(PERMISSION_ORDER_TRANSITION_OUT_OF_STOCK)
                                                        && $order->cancellingEligibility()) : ?>
                                            <a class="btn medium transparent" href="javascript:;" title="">
                                                <span class="button-content uppercase">
                                                    <i class="glyph-icon icon-remove"></i>
                                                    Hết Hàng
                                                </span>
            </a>
                                            <?php endif; ?>

                                            <?php if ($controller->isAllowed(PERMISSION_ORDER_EDIT_RECEIVED_QUANTITY)) : //Status for checking ?>

                                                {{#if need_checking}}
                                                    {{#if checked}}
                                                    <a class="btn medium transparent" href="javascript:;" title="">
                                                        <span class="button-content uppercase">ĐÃ KIỂM</span>
                                                    </a>
                                                    {{else}}
                                                    <a class="btn medium primary-bg" id="_checked" href="javascript:;" title="">
                                                                                            <span class="button-content uppercase">
                                                                                                <i class="glyph-icon icon-thumbs-up"></i>
                                                                                                Kiểm Xong
                                                                                            </span>
                                                    </a>
                                                    {{/if}}
                                                {{/if}}

                                            <?php endif; ?>

                                                <!-- Add change status @luuhieu -->
                                                <?php if ($controller->isAllowed(PERMISSION_ORDER_CHANGE_WAIT_DELIVERY)
                                                    && $order->isBeforeStatus(\Order::STATUS_WAITING_FOR_DELIVERY)) :?>
                                                    <?php if (\Order::STATUS_CHECKED == $order->getStatus()
                                                        || (!$order->needToChecking() && $order->isAfterStatus(\Order::STATUS_BOUGHT, true))) :?>
                                                        <a class="btn medium primary-bg" id="_change-wait-delivery" href="javascript:;" title="">
                                                            <span class="button-content uppercase">
                                                                CHỜ GIAO
                                                            </span>
            </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>

                                                <?php if ($controller->isAllowed(PERMISSION_ORDER_CHANGE_REQUEST_DELIVERY)
                                                    && \Order::STATUS_WAITING_FOR_DELIVERY == $order->getStatus()) :?>
                                                    <a class="btn medium primary-bg" id="_change-request-delivery" href="javascript:;" title="">
                                                        <span class="button-content uppercase">
                                                            Y/C GIAO HÀNG
                                                        </span>
            </a>
                                                <?php endif; ?>

                                                <?php if ($controller->isAllowed(PERMISSION_ORDER_CHANGE_DELIVERY)
                                                    && \Order::STATUS_CUSTOMER_CONFIRM_DELIVERY == $order->getStatus()) :?>
                                                    <a class="btn medium primary-bg" id="_change-delivery" href="javascript:;" title="">
                                                        <span class="button-content uppercase">
                                                            ĐÃ GIAO HÀNG
                                                        </span>
            </a>
                                                <?php endif; ?>
                                                <!--/ change status @luuhieu -->

                <?php if($controller->isAllowed(PERMISSION_COMPLAINT_SELLER_CREATE_NEW) && $order->getComplainSeller() == 0){ ?>
                    <a class="btn medium primary-bg" id="_btn-show-complaint-seller" href="javascript:;" title="">
                        <span class="button-content uppercase">
                            Khiếu nại người bán
                        </span>
                    </a>
                <?php } ?>
                <?php if( ( $controller->isAllowed(PERMISSION_COMPLAINT_SELLER_CAN_ACCEPT)
                                || $controller->isAllowed(PERMISSION_COMPLAINT_SELLER_CAN_REJECT) )
                                && $order->getComplainSeller() == 1){ ?>
                    <a class="btn medium primary-bg" id="_btn-doing-complaint-seller" href="javascript:;" title="">
                        <span class="button-content uppercase">
                            Đang khiếu nại người bán
                        </span>
                    </a>
                <?php } ?>

            </div>
        </div>

    </div>
</div>

<div class="module-title" id="_services_fee">
    <div class="col-lg-12 col-md-12" style="float:left; margin-bottom:10px">
        <div class="col-lg-5 col-md-5"></div>
        <div class="col-lg-7 col-md-7">
            <div class="_p_choose_services col-lg-4" style="margin-top:10px">
                <input type="checkbox" class="_chooseServices"
                <?php
                if(!$order->isBeforeStatus(\Order::STATUS_WAITING_FOR_DELIVERY))
                {
                ?>
                 disabled="disabled"<?php } ?> data-type="<?php echo \Services::TYPE_EXPRESS_CHINA_VIETNAM ?>" style="width: 10px" data-order-id="{{id}}" {{#if is_cpn}}checked="checked"{{/if}} > Chuyển phát nhanh

            </div>
            <div class="_p_choose_services col-lg-8" style="margin-top:10px">
            <?php

                 // vcheck fee wood crating
                //$order_service = \OrderService::findOneByOrderIdAndServiceCode( $order->getId(),\Services::TYPE_WOOD_CRATING );
                //if ( $order_service ) {
                   // if($order_service->getMoney()>0){
                        //$disable_checkbox_fee_wood_crating= false;
                    //}else{
                        //$disable_checkbox_fee_wood_crating= true;
                    //}
                //}else{
                    //$disable_checkbox_fee_wood_crating= false;
               // }
            ?>
            <input type="checkbox" class="_chooseServices" <?php if(!$controller->isAllowed(PERMISSION_ORDER_EDIT_SERVICES_REQUEST)){ ?>disabled="disabled"<?php } ?> data-type="<?php echo \Services::TYPE_WOOD_CRATING ?>" style="width: 10px" data-order-id="{{id}}" {{#if is_wood_crating}}checked="checked"{{/if}} >Thêm phí đóng gỗ
                <?php if($controller->isAllowed(PERMISSION_ORDER_EDIT_FEES)){?>

                <a style="float: right; margin-top: -9px;" title="" data-toggle="modal" data-target="#checkwood" href="javascript:;"  class="_span_fee_wood_crating btn medium primary-bg {{#if is_wood_crating}} {{else}} hide{{/if}}"  >
                <span class="button-content uppercase ">
                    Thêm phí đóng gỗ
                </span>
            </a>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="item-title title">
            <div class="col-lg-12 col-md-3">
                <h3 class="font-black">LS giao dịch </h3>
            </div>
        </div>

        <div class="item-title">
            <div class="col-lg-6 col-md-6">
                <div class="left-title font-gray">Mã giao dịch</div>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="left-title font-gray">Loại GD</div>
            </div>

            <div class="col-lg-3 col-md-3">
                <div class="left-title font-gray">Số tiền</div>
            </div>
        </div>

        <div id="_show-list-transaction-order"></div>

    </div>

    <div class="col-lg-6 col-md-6 _fee " id="list_fee"></div>


    <!--<div class="col-lg-12 col-md-12">-->

        <!--<div class="row">-->
            <!--<div class="col-md-12 col-lg-12">-->
                <!--<p class="title">Khiếu nại người bán của đơn hàng</p>-->
                <!--<div class="module-float ">-->
                    <!--<div class="module-float header-top font-gray">-->
                        <!--<div class="col-lg-1 col-md-1">id</div>-->
                        <!--<div class="col-lg-3 col-md-3">-->
                            <!--<p class="text-left">Lí do</p>-->
                        <!--</div>-->
                        <!--<div class="col-lg-2 col-md-2">-->
                            <!--<p>Tình trạng</p>-->
                        <!--</div>-->
                        <!--<div class="col-lg-2 col-md-2">-->
                            <!--<p>Hạn xử lý</p>-->
                        <!--</div>-->
                        <!--<div class="col-lg-2 col-md-2">-->
                            <!--<p>Đã đòi được</p>-->
                        <!--</div>-->

                        <!--<div class="accout"><p class="text-left">Tiếp nhận</p></div>-->
                    <!--</div>-->

                    <!--<div class="module-float list" id="_list-complaint-sellers"></div>-->

                    <!--<div id="_show-paging-complaint-seller"></div>-->
                <!--</div>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->

    <!--<div class="col-lg-12 col-md-12">-->
        <!--<div class="row" id="_show-table-complaints">-->
            <!--<div class="col-md-12 col-lg-12">-->
                <!--<p class="title">Khiếu nại dịch vụ của đơn hàng</p>-->

                <!--<div class="module-float ">-->
                    <!--<div class="module-float header-top font-gray">-->
                        <!--<div class="col-lg-1 col-md-1">id</div>-->
                        <!--<div class="col-lg-4 col-md-4">-->
                            <!--<p class="text-left">Tên khiếu nại</p>-->
                        <!--</div>-->
                        <!--<div class="col-lg-2 col-md-2">-->
                            <!--<p class="text-left">Lý do</p>-->
                        <!--</div>-->
                        <!--<div class="col-lg-2 col-md-2">-->
                            <!--<p>Tình trạng</p>-->
                        <!--</div>-->
                        <!--<div class="col-lg-2 col-md-2">-->
                            <!--<p>Tiếp nhận</p>-->
                        <!--</div>-->

                        <!--<div class="accout"><p class="text-left">Tiếp nhận</p></div>-->
                    <!--</div>-->

                    <!--<div class="module-float list" id="_list-complaints"></div>-->

                    <!--<div id="_show-paging-complaint"></div>-->
                <!--</div>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->

</div>
</div>
<!--\order bottom -->
</div>
</div>
</div>
</div>
</div>
<!--/order info -->

<!-- RIGHT CHAT -->
<div class="sidebar-left seubox-chat summaryv2 seu-chat-tab _order_comment" id="seu-chat-tab-{{id}}" data-order-id="{{id}}">
    <div class="sidebar-left-header ">
        <h5 class="title">
            <span class="uppercase normal-blod">{{code}}</span>
                <span class="font-gray-dark font-small uppercase">
                     {{#if need_checking}}
                <small>(Có Kiềm Hàng)</small>
                {{else}}
                <small>(Không Kiểm)</small>
                {{/if}}
                </span>
        </h5>
    </div>
    <div class="item-side-left v2 top">
        <div class="module-content">
            <div class="item-chat-main">
                <div class="chat-box" id="box_external">

                </div>
            </div>
            <div class="item-chat form-input">
                <input id="msg_chat_external" class="textarea-no-resize" data-type="EXTERNAL" data-order-id="{{id}}" name="msg_chat"
                       <?php if(!$controller->isAllowed(PERMISSION_COMMUNICATE_CUSTOMER)){ ?>disabled="disabled" placeholder="Bạn không có quyền chat với khách"<?php }else{ ?>
                       placeholder="Chat với khách. Enter để gửi" <?php } ?>/>
                <span class="icon-chat font-gray-dark-dark"><i class="glyph-icon icon-comments"></i></span>
            </div>
            <div class="border-chat-top">
                <div class="line_through"></div>
            </div>
        </div>
    </div>
    <div class="item-side-left v2 bottom">
        <div class="module-content">
            <div class="item-chat-main">
                <div class="chat-box" id="box_internal">

                </div>
            </div>
            <div class="item-chat form-input">
                <input id="msg_chat_internal" class="textarea-no-resize" data-type="INTERNAL" data-order-id="{{id}}" name="msg_chat" placeholder="Chát với nội bộ. Enter để gửi" />
                <span class="icon-chat font-gray-dark-dark"><i class="glyph-icon icon-comments"></i></span>
            </div>
        </div>
    </div>
</div>
<!--/right chat -->
<!--popup cho phí đóng gỗ-->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="checkwood" class="modal fade finish-poup itemdetail" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×<span class="toll-close">Nhấn Esc để đóng</span></button>
                <h4 id="myModalLabel" class="modal-title"><p class="normal-blod title">Nhập phụ phí đóng gỗ</p></h4>
            </div>
            <div class="modal-body">
                <div class="module-float">
                    <div class="form-label col-lg-4 col-md-4 text-left">
                        <label for="">
                            Phí đóng gỗ :
                        </label>
                    </div>
                    <div class="col-md-8 col-md-8">
                        <input type="text" data-a-dec="," data-a-sep="." placeholder="Nhập phí đóng gỗ..." class="form-control form-myinput col-md-8 col-md-8" id="_money_wood_crating"><span style="margin:5px 0px 0px 10px;float:left">VNĐ</span>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button class="seubtn btn-blue pull-right " type="button" id="add_fee_wood_crating" rel="{{order_id}}">Thêm<span class="arow-disable"></span></button>
            </div>
        </div>
    </div>
</div>
<!--end popup them phi đóng gỗ-->
</script>

<script id="_order_chat_row_template" type="text/x-handlebars-template">
    {{#if is_chat}}
    <div class="module-item">
        <div class="position-avatar">
            <a href="user/detail/{{user_id}}" target="_blank" class="user-img-tool" title="" rel="tooltipbottom" data-original-title="@{{account}}">
                <img class="img-rounded" alt="" src="{{img_path}}">
            </a>
        </div>
        <p class="normal">
            <a class="font-black" href="user/detail/{{user_id}}" target="_blank">
                <span class="normal-blod">{{first_name}}</span>
            </a>
            <span class="font-gray-dark time pull-right">{{date sub_time}}</span>
        </p>
        <p class="normal">{{{message}}}</p>
    </div>
    {{/if}}
    {{#if is_log}}
    <div class="module-item">
        <p class="font-gray-dark">{{date sub_time}}</p>
        <p class="font-gray-dark">
            {{{message}}}
        </p>
    </div>
    {{/if}}
    {{#if is_activity}}
    <div class="module-item">
        <p class="font-gray-dark">{{date sub_time}}</p>
        <p class="font-gray-dark">
            {{#if is_internal}}
                <a class="font-gray" href="user/detail/{{user_id}}" title="{{first_name}}" target="_blank"><strong>{{first_name}}</strong></a>
            {{/if}}
            {{{message}}}
        </p>
    </div>
    {{/if}}
</script>

<script id="_list-item-template" type="text/x-handlebars-template">
    <!-- ITEM HEADER -->
    <div class="header-listcart">
        <div class="bg-id"></div>
        <div class="col-lg-6">
            <div class="col-lg-1">
                <p><input type="checkbox" id="chkall" name="chkall" value="chkall" /></p>
                <p class="font-gray-dark">ID</p>
            </div>
            <div class="col-lg-11">
                <p class="font-gray-dark">Sản Phẩm <span class="font-orange">({{total_item}})</span></p>
            </div>
        </div>
        <div class="col-lg-2">
            <p class="text-center font-gray-dark">Mẫu</p>
        </div>
        <div class="col-lg-2">
            <p class="text-center font-gray-dark">Đơn giá</p>
        </div>
        <div class="col-lg-2">
            <p class="text-center font-gray-dark">Số Lượng <span class="font-orange">({{total_quantity}})</span></p>
        </div>
    </div>
    <!--/ item header -->

    <div class="body-listorder">
        {{#if type}}
        {{#each items}}
        <div class="body-listorder-item {{#if is_odd }}v2{{/if}}" data-item-id="{{id}}" data-order-id="{{order_id}}" data-order-code="{{order_code}}" data-page-size="3" page="1">
            <div class="bg-id"></div>
            <div class="col-lg-6">
                <div class="col-lg-1">
                    {{#if edit_quantity}}
                    <input is_out_of_stock="0" is_receive_enough="0" type="checkbox" class="chk" name="chk" value="chk" />
                    {{else}}
                    <input disabled="disabled" is_out_of_stock="0" is_receive_enough="0" type="checkbox" class="chk" name="chk" value="chk" />
                    {{/if}}
                    <small>{{id}}</small>
                </div>
                <div class="col-lg-11">
                    <div class="module-listitem">
                        <div class="position-left img-avatar">
                            <a href="{{link}}" target="_blank">
                                <img class="item-image lazy" data-original="{{image}}" alt="">
                            </a>
                        </div>
                        <div class="content">
                            <p class="normal title">
                                <a href="{{link}}" target="_blank">
                                    {{#if title}}
                                    {{title}}
                                    {{else}}
                                    {{link}}
                                    {{/if}}
                                </a>
                                {{#if weight}}<span class="font-gray-dark note">({{weight}} kg)</span>{{/if}}
                            </p>
                            <p class="note">{{note}}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-2 text-center">
                <p class="normal">{{property_translated}}</p>
                <p class="normal font-gray-dark">({{property}})</p>
            </div>

            <div class="col-lg-2">
                <p class="text-center font-red">{{total_amount_recive_ndt}}<sup>¥</sup></p>
                <p class="text-center font-small font-gray-dark">({{recive_quantity}} x
                    {{#if price_cny}}
                    <span class="text-center">{{price_cny}}<sup>¥</sup></span>
                    {{else}}
                    <span class="text-center">0<sup>¥</sup></span>
                    {{/if}}
                    )
                </p>
                <p class="text-center font-red _money-amount-blue" data-amount="{{total_amount_recive_vnd}}">{{total_amount_recive_vnd}}</p>
                <p class="text-center font-small font-gray-dark">({{recive_quantity}} x
                    {{#if price}}
                    <span class="text-center _money-amount-gray" data-amount="{{price}}">{{price}}<sup>đ</sup></span>
                    {{else}}
                    <span class="text-center _money-amount-gray" data-amount="{{price}}">0<sup>đ</sup></span>
                    {{/if}}
                    )
                </p>
            </div>

            <div class="col-lg-2 sl">
                <div class="quantity">
                    {{#if edit_quantity}}
                    <div class="numbers-row">
                        <div class="dec button _qtyplus">-</div>
                        <input type="text" data-order-code="{{code}}" data-order-id="{{order_id}}" data-item-id="{{id}}" id="_item-receive-quantity-{{id}}" class="sl-input quantity" name="quantity" value="{{recive_quantity}}">
                        <div class="inc button _qtyminus">+</div>
                    </div>
                    {{else}}
                    <span class="receive-quantity" data-item-id="{{id}}">{{recive_quantity}}</span>
                    {{/if}}

                    <span class="pending-quantity" data-pending-quantity="{{pending_quantity}}" data-item-id="{{id}}">/ {{pending_quantity}}</span>
                    <span class="order-quantity" data-order-quantity="{{order_quantity}}" data-item-id="{{id}}">/ {{order_quantity}}</span>

                </div>

                <div class="link-sl">
                    <p>
                        {{#if edit_quantity}}
                        <a href="javascript:;" data-order-code="{{code}}" class="font-red _item-change-out-of-stock" data-item-id="{{id}}">Hết hàng</a> |
                        <a href="javascript:;" data-item-id="{{id}}" class="_item-change-pendding-quantity">Nhận đủ</a>
                        {{/if}}
                    </p>
                </div>
            </div>

            <!--
            <div class="col-lg-2 sl">
                <p class="text-center">
                    <span class="receive-quantity" data-item-id="{{id}}" id="_current-item-receive-quantity-{{id}}">{{recive_quantity}}</span>
                    /
                    <span class="pending-quantity" data-item-id="{{id}}">{{pending_quantity}}</span>
                    /
                    <span class="order-quantity" data-item-id="{{id}}">{{order_quantity}}</span></p>

                {{#if edit_quantity}} {{/if}}
                <div class="addsl">
                    <div class="module">
                        <div class="quantity-input">
                            <input type="button" field="quantity" class="qtyminus" value="-">
                            <input type="text" data-item-id="{{id}}" id="_item-receive-quantity-{{id}}" class="sl-input" name="quantity" value="{{recive_quantity}}">
                            <input type="button" field="quantity" class="qtyplus" value="+">
                        </div>
                        <div class="quantity-quick-tool">
                            <a href="javascript:;" class="font-red _item-change-out-of-stock" data-item-id="{{id}}">Hết Hàng</a>
                        </div>
                    </div>
                </div>

            </div>
            -->

            <div id="chat-item-body-{{order_id}}-{{id}}" class="chat-item-body col-lg-6 col-lg-offset-3">
                <div class="seu-chat-item-order form-input">
                    <div class="input-append-wrapper input-append-right">
                        <div class="append-right">
                            <input loaded="0" type="text" name="" class="_item_input_chat" data-item-id="{{id}}"
                                   data-order-id={{order_id}} placeholder="Chát nội bộ về sản phẩm...">
                            <a data-original-title="Reply" href="javascript:;" class="btn input-append primary-bg _btn_send_message" title="">
                                <i class="glyph-icon icon-mail-reply"></i>
                            </a>
                        </div>
                        <!--Box Item comment-->
                        <div class="content-chat-item _content_chat_item" data-item-id="{{id}}">
                            <div class="_content_chat_item_view"><span class="normal-blod">{{username}}</span>{{{message}}}</div>
                        </div>
                    </div>
                    <div class="show-chat-item">
                        <span style="display: none;" id="show-more-item-comment-{{order_id}}-{{id}}" page="2" data-page-size="3" class="font-blue _view_item_chat" data-order-id="{{order_id}}" data-item-id="{{id}}">Xem thêm 3 chát nữa <i class="glyph-icon font-blue icon-caret-down"></i></span>
                    </div>

                </div>
            </div>

        </div>
        {{/each}}
        {{else}}
        <div class="infobox warning-bg" id="_item-list-error">
            <p>{{message}}</p>
        </div>
        {{/if}}
    </div>
    </div>

</script>

<div id="_order-detail-placeholder"></div>

<script id="_box-guide" type="text/x-handlebars-template">

    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModalalert" class="modal fade finish-poup itemdetail" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×<span class="toll-close">Nhấn Esc để đóng</span></button>
                    <h3 id="myModalLabel" class="modal-title"><p class="text-left normal-blod title">Hướng dẫn</p></h3>
                </div>
                <div class="modal-body">
                    <div class="item-module-popup trlg">
                        <div class="module-title font-bold"> Nhập trọng lượng</div>
                        <div class="col-lg-6 col-md-6 col-sm-6 content">
                            <p> - Nhập số gram</p>
                            <p> - VD: 1600gram(1,6kg)</p>
                            <p> - Enter hoặc click vào nút lưu</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 pull-right">

                            <img alt="" src="assets/images/trongluong.jpg" />
                        </div>
                    </div>
                    <div class="item-module-popup checkut">
                        <div class="module-title font-bold"> Sửa số lượng khi kiểm hàng</div>
                        <div class="col-lg-8 col-md-8 col-sm-8 content">
                            <p> - Hiển thị số lượng ---- Số lượng kiểm / Số lượng mua / Số lượng đặt</p>
                            <p> - Di chuột lên vùng sản phẩm sẽ hiển thị như hình bên.</p>
                            <p> - Click ( <span><img alt="" src="assets/images/arow-ali-up.png"/></span> ) để tăng hoặc ( <span><img alt="" src="assets/images/arow-ali.png"/></span> ) để giảm số lượng.</p>
                            <p> - Có thể sửa số lượng trực tiếp trong ô nhập liệu.</p>
                            <p> - Click " hết hàng " để chuyển số lượng về 0.</p>
                            <p> - Click " nhận đủ " để chuyển số lượng = số lượng mua.</p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <img class="img" alt="" src="assets/images/kiemhang.jpg"/>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>

</script>



<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModalalert1" class="modal fade finish-poup _panel-complaint-seller">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×<span class="toll-close">Nhấn Esc để đóng</span></button>
                <h3 id="myModalLabel" class="modal-title"><p class="text-left normal-blod title">Khiếu nại người bán</p></h3>
            </div>
            <div class="modal-body">
                <input type="hidden" id="_complaint-seller-order_id" value="<?php echo $order->getId(); ?>" />

                <div class="col-lg-5 col-md-5 text-right">
                    Lý do đòi tiền:
                </div>
                <div class="col-lg-7 col-md-7">
                    <select class="cat" id="_complaint-seller-reason">
                        <option value="">Vui lòng chọn một lý do đòi tiền</option>
                        <?php
                        $reasons = \ComplaintSeller::$reasonTitle;
                        foreach((array)$reasons as $key => $value){
                            echo "<option value='" . $key . "'>" . $value . "</option>";
                        }
                        ?>
                    </select>
                </div>


                <div class="col-lg-5 col-md-5 text-right">
                    Hạn xử lý:
                </div>
                <div class="col-lg-7 col-md-7">
                    <input style="margin-top: 10px;" id="_complaint-seller-refocus-time" type="text" value="<?php echo date("d-m-Y"); ?>" placeholder="" />
                </div>

                <div class="col-lg-5 col-md-5"></div>
                <div class="col-lg-7 col-md-7" id="_complaint-seller-message-error"></div>

            </div>
            <div class="modal-footer">
                <div class="col-lg-12 col-md-12">
                    <a id="_btn-save-complaint-seller" href="javascript:void(0)" class="btn medium primary-bg font-white">
                        <span style="text-transform: uppercase;" class="button-content">Lưu</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModalalert2" class="modal fade finish-poup _panel-complaint-seller">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×<span class="toll-close">Nhấn Esc để đóng</span></button>
                <h3 id="myModalLabel" class="modal-title"><p class="text-left normal-blod title">Kết thúc khiếu nại</p></h3>
            </div>
            <div class="modal-body">
                <div class="col-lg-5 col-md-5 text-right">
                    Trạng thái hoàn thành:
                </div>
                <div class="col-lg-7 col-md-7">
                    <select id="_complaint-seller-status">
                        <?php if($controller->isAllowed(PERMISSION_COMPLAINT_SELLER_CAN_ACCEPT)){ ?>
                            <option value="SUCCESS">Thành công</option>
                        <?php } ?>
                        <?php if($controller->isAllowed(PERMISSION_COMPLAINT_SELLER_CAN_REJECT)){ ?>
                            <option value="FAILURE">Thất bại</option>
                        <?php } ?>
                    </select>
                </div>

                <?php if($controller->isAllowed(PERMISSION_COMPLAINT_SELLER_CAN_ACCEPT)){ ?>
                    <div id="_complaint-seller-status-success">
                        <div class="col-lg-5 col-md-5 text-right">
                            Số tiền đòi được (NDT):
                        </div>
                        <div class="col-lg-7 col-md-7">
                            <input data-a-sep="." data-a-dec="," style="margin-top: 10px;" id="_complaint-seller-amount-seller-refund" type="text" value="0" placeholder="" />
                        </div>

                        <div class="col-lg-5 col-md-5 text-right">
                            Ghi chú:
                        </div>
                        <div class="col-lg-7 col-md-7">
                            <textarea id="_complaint-seller-description" style="margin-top: 10px;"></textarea>
                        </div>
                    </div>
                <?php } ?>

                <div class="col-lg-5 col-md-5"></div>
                <div class="col-lg-7 col-md-7" id="_complaint-seller-message-error"></div>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12 col-md-12">
                    <a id="_btn-save-complaint-seller-status" href="javascript:void(0)" class="btn medium primary-bg font-white">
                        <span style="text-transform: uppercase;" class="button-content">Lưu</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Các phí trên đơn -->
<script id="_render_fee" type="text/x-handlebars-template">
    <div class="item-title title">
        <div class="col-lg-12 col-md-12">
            <h3 class="main-header-title font-black">Các phí trên đơn</h3></div>
    </div>

    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark">Tiền hàng(1)</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-black font-bold" data-amount="{{real_amount}}">{{real_amount}}</p>
        </div>
    </div>

    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark" style="font-weight: bold">Tổng phí(2)</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-black font-bold" data-amount="{{total_services_fee}}">{{total_services_fee}}</p>
        </div>
    </div>

    {{#each order_services}}
    <div class="item-bottom _services-fee" >
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark">
                Phí {{description}}
            </p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-black _money_services" data-type="{{service_code}}" data-amount="{{money}}">
                {{money}}
            </p>
        </div>
    </div>
    {{/each}}

    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark">Tổng giá trị đơn(3) ( = 1 + 2)</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-blue font-bold" data-amount="{{total_amount}}">{{total_amount}}</p>
        </div>
    </div>
    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark">Trả lại(4)</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-black font-bold" data-amount="{{real_refund_amount}}">{{real_refund_amount}}</p>
        </div>
    </div>
    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark font-bold">Đã thanh toán(5)</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-black font-bold" data-amount="{{real_payment_amount}}">{{real_payment_amount}}</p>
        </div>
    </div>

    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark">Đặt cọc(6)</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-black font-bold" data-amount="{{deposit_amount}}">{{deposit_amount}}</p>
        </div>
    </div>

    <div class="item-bottom">
        <div class="col-lg-7 col-md-7">
            <p class="font-gray-dark">Còn thiếu (7) = (3+4) - 5</p>
        </div>
        <div class="col-lg-5 col-md-5">
            <p class="_money-amount-red font-bold" data-amount="{{missing_amount}}">{{missing_amount}}</p>
        </div>
    </div>
</script>
<!-- Kết thúc các phí trên đơn -->

<!-- BEGIN TEMPLATE KNNB -->
<script id="_item-row-complaint-seller" type="text/x-handlebars-template">
    <div class="module-float main-ct">
        <div class="module-float">
            <div class="col-lg-1 col-md-1">
                {{id}}
            </div>
            <div class="col-lg-3 col-md-3">
                <p class="text-left">{{reason_title}}</p>
            </div>
            <div class="col-lg-2 col-md-2">
                <p class="uppercase font-bold">{{status_title}}</p>
            </div>
            <div class="col-lg-2 col-md-2">
                <p class="font-red">{{refocus_time}}</p>
            </div>
            <div class="col-lg-2 col-md-2">
                <p>{{amount_seller_refund}} NDT</p>
            </div>

            <a class="user-acc" href="ComplaintSeller/detail/{{id}}" title="">
                {{#if processed_by}}
                <div class="img-acc">
                    <div class="avatar">
                        <img src="{{info_processed.avatar}}" alt="" />
                    </div>
                    <i class="fa fa-chevron-right"></i>
                </div>
                {{/if}}
            </a>

            <div class="border-left"></div>
        </div>
    </div>
</script>
<!-- END TEMPLATE KNNB -->

<!-- BEGIN KNDV -->
<script id="_item-row-complaint" type="text/x-handlebars-template">
    <div class="module-float main-ct">
        <div class="module-float">
            <div class="col-lg-1 col-md-1">{{id}}</div>
            <div class="col-lg-4 col-md-4">
                <p class="text-left">
                    {{title}}
                </p>
            </div>
            <div class="col-lg-2 col-md-2">
                <p class="text-left">{{type_title}}</p>
            </div>
            <div class="col-lg-2 col-md-2">
                <p class="font-bold uppercase">{{status_title}}</p>
            </div>
            <div class="col-lg-2 col-md-2">
                <p>{{recipient_time}}</p>
            </div>
            <a target="_blank" href="complaint/detail/{{id}}">
                <div class="img-acc">
                    <div class="avatar">
                        {{#if show_info_recipient_by}}
                        <img src="{{info_recipient_by.avatar}}">
                        {{/if}}
                    </div>
                    <i class="fa fa-chevron-right"></i>
                </div>
            </a>
            <div class="border-left"></div>
        </div>
    </div>
</script>
<!-- END KNDV -->

<!-- BEGIN LSGD -->
<script id="_list-transaction-order-tpl" type="text/x-handlebars-template">
    {{#each transaction_order}}
    <div class="item-bottom">
        <div class="item-title">
            <div class="col-lg-6 col-md-6">
                <p class="font-black">
                    <small>{{transaction_code}}</small>
                </p>
                <p class="font-gray-dark">
                    {{closed_time_format_type2}}
                </p>
            </div>
            <div class="col-lg-3 col-md-3">
                <p class="font-gray-dark">
                    {{transaction_type_title}}
                </p>
            </div>
            <div class="col-lg-3 col-md-3">
                <p class="_money-amount" data-amount="{{amount}}">
                    {{amount}}
                </p>
            </div>
        </div>
    </div>
    {{/each}}
</script>
<!-- END LSGD -->
