<?php

const PERMISSION_USER_VIEW = 'USER_VIEW';
const PERMISSION_USER_INFO_EDIT = 'USER_INFO_EDIT';
const PERMISSION_USER_ADDRESS_EDIT = 'USER_ADDRESS_EDIT';
const PERMISSION_USER_MOBILE_EDIT = 'USER_MOBILE_EDIT';
const PERMISSION_USER_VIEW_FINANCE = 'USER_VIEW_FINANCE';
const PERMISSION_USER_PROCURACY = 'USER_PROCURACY';

const PERMISSION_ROLE_VIEW = 'ROLE_VIEW';
const PERMISSION_ROLE_EDIT = 'ROLE_EDIT';
const PERMISSION_USER_ROLE_MANAGE = 'USER_ROLE_MANAGE';
const PERMISSION_ROLE_PERMISSION_MANAGE = 'ROLE_PERMISSION_MANAGE';

const PERMISSION_COMMUNICATE_CUSTOMER = 'COMMUNICATE_CUSTOMER';
const PERMISSION_PUBLIC_PERSONAL_INFO = 'PUBLIC_PERSONAL_INFO';

const PERMISSION_CANCEL_ORDER = 'CANCEL_ORDER';
const PERMISSION_APPOINTMENT_ORDER = 'APPOINTMENT_ORDER';
const PERMISSION_ORDER_EDIT_FEES = 'ORDER_EDIT_FEES';
const PERMISSION_ORDER_PACKAGING_SURCHARGES = 'ORDER_PACKAGING_SURCHARGES';
const PERMISSION_ORDER_PAYMENT = 'ORDER_PAYMENT';
const PERMISSION_ORDER_EDIT_PRICE = "ORDER_EDIT_PRICE";

const PERMISSION_ORDER_ADD_FREIGHT_BILL = 'ORDER_ADD_FREIGHT_BILL';
const PERMISSION_ORDER_EDIT_FREIGHT_BILL = 'ORDER_EDIT_FREIGHT_BILL';
const PERMISSION_ORDER_EDIT_INVOICE = 'ORDER_EDIT_INVOICE';
const PERMISSION_ORDER_ADD_INVOICE = 'ORDER_ADD_INVOICE';

const PERMISSION_ORDER_VIEW_ORDER_DETAIL = 'ORDER_VIEW_ORDER_DETAIL';
const PERMISSION_ORDER_VIEW_ORDER_MANAGE = 'ORDER_VIEW_ORDER_MANAGE';
const PERMISSION_ORDER_VIEW_PURCHASE_MANAGE = 'ORDER_VIEW_PURCHASE_MANAGE';
const PERMISSION_ORDER_DELETE_ORDER = 'ORDER_DELETE_ORDER';
const PERMISSION_ORDER_VIEW_HISTORY = 'ORDER_VIEW_HISTORY';
const PERMISSION_ORDER_VIEW_TRANSACTION = 'ORDER_VIEW_TRANSACTION';
const PERMISSION_ORDER_TRANSITION_OUT_OF_STOCK = 'ORDER_TRANSITION_OUT_OF_STOCK';
const PERMISSION_ORDER_VIEW_ITEMS = 'ORDER_VIEW_ITEMS';
const PERMISSION_ORDER_EDIT_ORDER_QUANTITY = 'ORDER_EDIT_ORDER_QUANTITY';
const PERMISSION_ORDER_EDIT_PENDING_QUANTITY = 'ORDER_EDIT_PENDING_QUANTITY';
const PERMISSION_ORDER_EDIT_RECEIVED_QUANTITY = 'ORDER_EDIT_RECEIVED_QUANTITY';
const PERMISSION_ORDER_EDIT_WEIGHT = 'ORDER_EDIT_WEIGHT';
const PERMISSION_ORDER_EDIT_SERVICES_REQUEST = 'ORDER_EDIT_SERVICE_REQUEST';
const PERMISSION_ORDER_VIEW_SHIPPING_ADDRESS = 'ORDER_VIEW_SHIPPING_ADDRESS';
const PERMISSION_ORDER_VIEW_DELIVERY_MANAGEMENT = 'ORDER_VIEW_DELIVERY_MANAGEMENT';
const PERMISSION_ORDER_CHANGE_TRANSPORTING = 'ORDER_TO_TRANSPORTING';
const PERMISSION_ORDER_CHANGE_WAIT_DELIVERY = 'ORDER_TO_WAIT_DELIVERY';
const PERMISSION_ORDER_CHANGE_REQUEST_DELIVERY = 'ORDER_TO_REQUEST_DELIVERY';

const PERMISSION_ORDER_CUSTOMER_CONFIRM = 'ORDER_CUSTOMER_CONFIRM';

const PERMISSION_ORDER_CHANGE_DELIVERY =  'ORDER_TO_DELIVERY';
const PERMISSION_DELIVERY_CHANGE_COD =  'DELIVERY_CHANGE_COD';
const PERMISSION_DELIVERY_CHANGE_REAL_COD =  'DELIVERY_CHANGE_REAL_COD';
const PERMISSION_DELIVERY_CHANGE_SHIPPING_FEE =  'DELIVERY_CHANGE_SHIPPING_FEE';
const PERMISSION_DELIVERY_VIEW =  'DELIVERY_VIEW';
const PERMISSION_DELIVERY_VIEW_BILL_MANAGE =  'DELIVERY_VIEW_BILL_MANAGE';


const PERMISSION_COMPLAINT_CHAT_EXTERNAL = 'COMPLAINT_CHAT_EXTERNAL';
const PERMISSION_COMPLAINT_CAN_PROCESSING = 'COMPLAINT_CAN_PROCESSING';
const PERMISSION_COMPLAINT_CAN_ACCEPT = 'COMPLAINT_CAN_ACCEPT';
const PERMISSION_COMPLAINT_CAN_REJECT = 'COMPLAINT_CAN_REJECT';
const PERMISSION_COMPLAINT_CAN_APPROVAL = 'COMPLAINT_CAN_APPROVAL';
const PERMISSION_COMPLAINT_VIEW_LIST = 'COMPLAINT_VIEW_LIST';
const PERMISSION_COMPLAINT_CAN_RECEPTION = 'COMPLAINT_CAN_RECEPTION';
const PERMISSION_COMPLAINT_CAN_PROPOSED_AMOUNT = 'COMPLAINT_CAN_PROPOSED_AMOUNT';
const PERMISSION_COMPLAINT_CAN_CENSORSHIP_FINANCICAL = 'COMPLAINT_CAN_CENSORSHIP_FINANCICAL';

const PERMISSION_COMPLAINT_SELLER_VIEW_LIST = 'COMPLAINT_SELLER_VIEW_LIST';
const PERMISSION_COMPLAINT_SELLER_CREATE_NEW = 'COMPLAINT_SELLER_CREATE_NEW';
const PERMISSION_COMPLAINT_SELLER_CAN_PROCESSING = 'COMPLAINT_SELLER_CAN_PROCESSING';
const PERMISSION_COMPLAINT_SELLER_CAN_ACCEPT = 'COMPLAINT_SELLER_CAN_ACCEPT';
const PERMISSION_COMPLAINT_SELLER_CAN_REJECT = 'COMPLAINT_SELLER_CAN_REJECT';

const PERMISSION_PURCHASE_SKIPS_TELLERS = 'PURCHASE_SKIPS_TELLERS';
const PERMISSION_PURCHASE_SKIPS_PAID_STAFF = 'PURCHASE_SKIPS_PAID_STAFF';
const PERMISSION_PURCHASE_SELECT_TELLERS = 'PURCHASE_SELECT_TELLERS';
const PERMISSION_PURCHASE_CHANGE_CONFIG = 'PURCHASE_CHANGE_CONFIG';
const PERMISSION_PURCHASE_ORDER = 'PURCHASE_ORDER';

const PERMISSION_UPLOAD_BARCODE = 'UPLOAD_BARCODE';
const PERMISSION_VIEW_UPLOADED_BARCODE_SCAN_FILES = 'VIEW_UPLOADED_BARCODE_FILES';
const PERMISSION_VIEW_BARCODE_TRACKING = 'VIEW_BARCODE_TRACKING';
const PERMISSION_DOWNLOAD_BARCODE_SCAN_FILE = 'DOWNLOAD_BARCODE_SCAN_FILE';

const PERMISSION_SYSTEM_MANAGE = 'SYSTEM_MANAGE';
const PERMISSION_SYSTEM_EXCHANGE_MANAGE = 'SYSTEM_EXCHANGE_MANAGE';
const PERMISSION_SYSTEM_CONFIG_MANAGE = 'SYSTEM_CONFIG_MANAGE';
const PERMISSION_SYSTEM_LOCATION_MANAGE = 'SYSTEM_LOCATION_MANAGE';


