


<div style="margin-right:400px;margin-left:100px;">
 <div class="form-row">
                    <div class="form-label col-md-4">
                        <label for="" class="label-description">
                            Title:
                            <span></span>
                        </label>
                    </div>
                    <div class="form-input col-md-8">
                       <?php echo $post->title;?>
                    </div>

                    
                   
  </div>
  <div class="form-row">
  					 <div class="form-label col-md-4">
                        <label for="" class="label-description">
                            Category:
                            
                        </label>
                    </div>
                     

                    <div class="form-input col-md-8">
                         <?php  echo $category ?> 
                    </div>

  </div>
<div class="form-row">
				<div class="form-label col-md-4">
                        <label for="" class="label-description">
                            Content:
                            
                        </label>
                 </div>
                  <div class="form-input col-md-8">	
                    
              		 <?php echo $post->content;?>
           			
           			  </div>	
           	
</div>
                    
              
         
</div>
