<?php

$document = $this->document();
$publicPath = $document->getPublicPath();
$cssPath = $publicPath . 'assets/css/';
$jsPathPro = $publicPath . 'assets/js/process/';
$jsPath = $publicPath . 'assets/js/';
$document->addJsVar('base_url', \SeuDo\Main::getHomeRouter()->createUrl('/'), 'TOP');
$document->addJsVar('url_login', \SeuDo\Main::getHomeRouter()->createUrl('Login/login'), 'TOP');
$document->addJsVar('url_register', \SeuDo\Main::getHomeRouter()->createUrl('Register/default'), 'TOP');
$document->addJsVar('LoginFacebookUrl',\SeuDo\Main::getHomeRouter()->createUrl('ConnectFacebook'),'TOP');
$document->addJs($jsPath.'jquery.lazyload.js',"TOP");
$document->addJs($jsPath.'jquery.loadingbar.js',"TOP");
$document->addCss($cssPath.'loadingbar.css',"TOP");

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <title><?php echo $document->title != '' ? $document->title : 'Seudo.vn' ?></title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
<!--        Load JS-->
        <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap-theme.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap-select.min.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>mytypo.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>header.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>owl.carousel.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $jsPath ?>rate/rateit.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>owl.theme.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>responsive.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>cssloading.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>loading.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>style.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>seudo.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>footer.css" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $cssPath ?>linkorder.css" rel="stylesheet" type="text/css" media="all">
        <?php echo $document->css(); ?>

        <script src="<?php echo $jsPath?>jquery-1.10.2.min.js"></script>

        <script type="text/javascript" src="<?php echo $publicPath ?>assets/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $publicPath;?>assets/bootstrap/js/bootstrap-select.min.js"></script>
        <script type="text/javascript" src="<?php echo $jsPath;?>owl.carousel.min.js"></script>
        <script type="text/javascript" src="<?php echo $jsPath;?>rate/jquery.rateit.min.js"></script>
        <script type="text/javascript" src="<?php echo $jsPath;?>jqueryui.js"></script>
        <script type="text/javascript" src="<?php echo $jsPath;?>masonry.pkgd.js"></script>
        <script type="text/javascript" src="<?php echo $jsPathPro;?>order_link_base.js"></script>
        <!--<script type="text/javascript" src="<?php /*echo $jsPathPro;*/?>/include/global.js"></script>-->
        <script type="text/javascript" src="<?php echo $publicPath;?>assets/js/seudo-frontend.js"></script>
        <?php
        echo $document->js('TOP');
        ?>
    </head>
    <body>
    <div class="loading-data _loading" style="display: none">
        <div class="content">
            Đang tải dữ liệu <span>...</span>
        </div>
    </div>

    <div style="display: none;" class="modal fade finish-poup" id="_alert" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel"><span class="uppercase normal-blod">Thông báo</span></h4>
                </div>
                <div class="modal-body">
                    <p class="price-red1 _message"></p>
                </div>
                <div class="modal-footer">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <button type="button" class="btn btn-red btn-sm _delete_item">Đồng ý</button>
                    </div>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    <span class="remove _alert hidden" data-target="_alert" data-toggle="modal"></span>
        <!--  Header -->
        <?php
        $this->widget('app.Widget.Header', array(
            'user' => BaseAuth::getInstance()->getUser()
        ));
        ?>
        <!-- End Header -->


        <!-- Main Content -->
        <div id="_main_content">
        <?php echo $buffer; ?>
        </div>
        <!-- End Content -->

        <!-- Footer -->
        <?php $this->widget('app.Widget.Footer'); ?>
        <!-- End footer -->

   <div id="fb-root"></div>
   <script>(function(d, s, id) {
           var js, fjs = d.getElementsByTagName(s)[0];
           if (d.getElementById(id)) return;
           js = d.createElement(s); js.id = id;
           js.src = "<?php echo $jsPath ?>/all.js";
           fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));</script>
    </body>

    <?php
    echo $document->js('BOTTOM');
    ?>
</html>