<?php
use SeuDo\Main;
$document = $this->document();
$publicPath = Main::getUserUrl();
$cssPath = $publicPath . 'assets/css/';
$jsPath = $publicPath . 'assets/js/';
$imgPath = $publicPath . 'assets/images/';
$document->addJs($jsPath . 'profile.js', 'TOP');
$document->title = t("Đổi mật khẩu");
$publicPathHome = Main::getHomeUrl();
$jsPathHome = $publicPathHome . 'assets/js/';
$document->addJs($jsPathHome . 'jquery.password_strength.js', 'BOTTOM-USER');

?>
<div class="module-inner">
<div class="module-title">
    <p class="title"><span class="title-page">Đổi mật khẩu</span></p>
</div>
<div class="module-ct">
    <div class="item-profile row address-home">
    </div>
    <form class="custom" method="" id="frm-change-pass" onsubmit="return changePass();">
        <div class="item-profile row address-home">
            <div class="col-lg-2 col-md-2 col-sm-2">
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2">
                <span class="normal-blod titie-date">Mật khẩu hiện tại:</span>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <input type="password" name="input[pwd]" id="pwd" placeholder="" class="form-control form-myinput pull-right">
                <p class="red-normal" id="error-pwd"></p>
            </div>
        </div>
        <div class="item-profile row address-home">
            <div class="col-lg-2 col-md-2 col-sm-2">
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2">
                <span class="normal-blod titie-date">Mật khẩu mới:</span>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <input class="form-control form-myinput pull-right" type="password" name="input[newpwd]" id="newpwd" placeholder="">
                <p class="red-normal" id="error-newpwd"></p>
            </div>
        </div>
        <div class="item-profile row address-home">
            <div class="col-lg-2 col-md-2 col-sm-2">
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2">
                <span class="normal-blod titie-date">Nhập lại mật khẩu mới:</span>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <input class="form-control form-myinput pull-right" type="password" id="re_newpwd" name="input[re_newpwd]" placeholder="">
                <p class="red-normal" id="error-renewpwd"></p>
            </div>
        </div>
        <div class="item-profile row address-home">
            <div class="col-lg-2 col-md-2 col-sm-2">
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <p class="submit">
                    <button id="btnSubmit" class="btn btn-blue" type="button">Xác nhận</button>
                    <button id="btnWaiting" class="btn btn-blue hidden" type="button">Đang xác nhận...</button>
                </p>
            </div>
        </div>

    </form>
</div>
    <div class="module-ct">
    </div>
</div>


