<div id="page-title">
    <h3>
        Thêm địa điểm
    </h3>
    <div id="breadcrumb-right">

        <div class="float-right">                           

            <div class="dropdown">
                <a data-toggle="dropdown" title="Option" class="btn medium bg-white" href="javascript:;">
                    <span class="button-content">
                        <i class="glyph-icon icon-cog float-left"></i>
                        <i class="glyph-icon icon-caret-down float-right"></i>
                    </span>
                </a>
                <ul role="menu" class="dropdown-menu pad0A float-right">
                    <li><a href="<?php echo $this->createUrl('location/add') ?>"><i class="glyph-icon icon-plus"></i> Thêm địa điểm</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php
$html = '<select name="category" size="6" style="height:300px">';
foreach ($menu as $key => $value) {
    $string = '';
    for ($i = 0; $i < $value['level']; $i++) {
        $string.='----';
    }
    $row = '<option value="' . $value['id'] . '">' . $string . $value['label'] . '</option>';
    $html.=$row;
}
$html.='</select>';
?>



<?php
//$form = new \Flywheel\Html\Form();
$form = $this->createFrom('user_frm');
$form->setHtmlOption(array(
    'class' => 'form-horizontal',
));
$form->beginForm();
?>

<div class="col-md-8 form-label-right">
    <div class="form-row">
        <div class="form-label col-md-4">
            <label for="" >
                Tên địa điểm
                <span class="required">*</span>
            </label>
        </div>
        <div class="form-input col-md-8">
            <input type="name"  name="label" value ="">                        

        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-4">
            <label for="" >
                Ordering:
            </label>
        </div>
        <div class="form-input col-md-8">
            <input type="name"  name="ordering" value ="0">
        </div>

    </div>
    <div class="form-row">
        <div class="form-label col-md-4">
            <label for="" >
                Danh mục cha
                <span class="required">*</span>
            </label>
        </div>
        <div class="form-input col-md-8">
            <?php echo $html; ?>
        </div>



    </div>
    <div style="text-align: center ;"> 
        <button    class=" btn medium bg-blue-alt">  Submit  </button> 
    </div> 

</div>




<?php
$form->endForm();
?>