<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
//        js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=1449847118569980";
        js.src = "<?php echo $homeUrl ?>assets/js/all1.js#xfbml=1&appId=1449847118569980";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>