<?php
use SeuDo\Main;
/** @var \Backend\Controller\BackendBase $controller */
/** @var  $document */
$document = $this->document();
$publicPath = Main::getBackendUrl();
$publicPathHome = Main::getHomeUrl();
$assets = new \Flywheel\Asset\Asset('backend');
$jsPathHome = $publicPathHome . 'assets/js/';
$jsPath = $publicPath . 'assets/js/';
$imgPath = $publicPath . 'assets/images/';
$user = BackendAuth::getInstance()->getUser();
$items = @$items;

//$document->addJs('js/zopim.js', 'BOTTOM');
//$document->addJs('js/zopim.js', 'BOTTOM-USER');
//$document->addJsVar('zopim_username',$user->getUsername(),'BOTTOM');
//$document->addJsVar('zopim_email',$user->getEmail(),'BOTTOM');
//$document->addJs('js/getUsernameEmailZopim.js', 'BOTTOM');

?>

<span class="remove _alert hidden" data-target="#_alert" data-toggle="modal">alert</span>
<div style="display: none;" class="modal fade finish-poup" id="_alert" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="text-align: center">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"><span class="uppercase normal-blod">Thông báo</span></h4>
            </div>
            <div class="modal-body">
                <p class="price-red1 _message"></p>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12"  style="text-align: center">
                    <button type="button" style="font-size: 13px; width: 80px; height: 30px;" class="btn btn-red btn-sm" data-dismiss="modal">Đồng ý</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<span class="remove _confirm hidden" data-target="#_confirm" data-toggle="modal">confirm</span>
<div style="display: none;" class="modal fade finish-poup" id="_confirm" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="text-align: center">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"><span class="uppercase normal-blod">Thông báo</span></h4>
            </div>
            <div class="modal-body">
                <p class="price-red1 _message"></p>
            </div>
            <div class="modal-footer">
                <div class="col-lg-12"  style="text-align: center">
                    <button id="_btn-agree-confirm" type="button" style="font-size: 13px; width: 80px; height: 30px;" class="btn btn-red btn-sm" data-dismiss="modal">Đồng ý</button>
                    <button type="button" style="font-size: 13px; width: 80px; height: 30px;" class="btn btn-default btn-sm" data-dismiss="modal">Từ chối</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<div class="module-back-top hidden">
    <p> <i class="fa fa-arrow-up"></i> </p>
    <p style="font-size: 10px">TOP</p>
</div>

<nav class="note-page container">
    <div class="module-float note-alert">
        <p><i style="" class="fa fa-warning"></i>Số dư khách âm hoặc số tiền cần thu tối thiểu âm (&lt;0) là khách thiếu tiền</p>
    </div>
</nav>

<nav role="navigation" class="container header-top">
    <div class="row">
        <div class="col-lg-1 col-md-1">
            <div class="module-float logo">
                <a href="#"></a>
            </div>
        </div>

        <div class="col-lg-4 col-md-4">
            <div class="module-float input-search hidden">
                <input type="text" id="exampleInput" class="form-control form-myinput" placeholder="Tìm đơn hàng nhanh theo mã đơn hàng hoặc ID...">
                <a href="#"><span class="arrow"></span></a>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 pull-right">
            <div class="user-profile dropdown">
                <a data-toggle="dropdown" class="pull-right user-ico clearfix" title="" href="javascript:;">
                    <img width="36" alt="" src="<?php echo \Users::getAvatar32x($user);?>">
                    <span><?php echo $user->getUsername();?></span>
                    <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu float-right">
                    <i class="fa fa-sort-asc dropdown-arrow"></i>
                    <li>
                        <a title="" href="<?php echo $controller->createUrl('user/user_profile/edit');?>">
                            <i class="fa fa-user"></i>
                            <span class="font-bold">Thông tin cá nhân</span>
                        </a>
                    </li>
                    <li>
                        <a title="" href="<?php echo $controller->createUrl('login/logout');?>">
                            <i class="fa fa-sign-out"></i>
                            <span class="font-bold">Logout</span>
                        </a>
                    </li>
                    <!--        <li class="divider"></li>-->

                </ul>
            </div>
        </div>
    </div>
</nav>