<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: none !important; height: 100% !important; font-family:arial; width: 100% !important; min-width: 100% !important; background-color: #dddddd; margin: 0; padding: 0;";>
<center>

    <h3 style="padding-top: 10px;">Đơn hàng đã mua lớn hơn 3 ngày không có mã vận đơn (<?php echo sizeof($data['order1']); ?>)</h3>
    <?php if(sizeof($data['order1']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
                <?php $count = 0; ?>
                <?php foreach($data['order1'] as $order){ ?>
                    <?php if($order instanceof \Order){ ?>
                        <?php
                            $count++;
                            $order_id = $order->getId() ? (int)$order->getId() : 0;
                            $order_code = $order->getCode() ? $order->getCode() : "";
                            $order_status = $order->getStatus() ? $order->getStatus() : "";
                            $problems = "Đơn hàng đã mua lớn hơn 3 ngày không có mã vận đơn";
                            $time = "";
                            if($order->getBoughtTime()){
                                $time = date('d/m/Y', strtotime($order->getBoughtTime()));
                            }
                            $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                        ?>
                        <tr>
                            <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                            <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                            <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                            <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                            <td width="40%" style="text-align: left; padding: 5px;">
                                <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã mua lớn hơn 5 ngày không có mã vận đơn (<?php echo sizeof($data['order2']); ?>)</h3>
    <?php if(sizeof($data['order2']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
        <thead>
        <tr>
            <th>STT</th>
            <th>Mã đơn hàng</th>
            <th>Trạng thái</th>
            <th>Thời gian mua hàng</th>
            <th>Link đơn hàng</th>
        </tr>
        </thead>
        <tbody>
            <?php $count = 0; ?>
            <?php foreach($data['order2'] as $order){ ?>
                <?php if($order instanceof \Order){ ?>
                    <?php
                    $count++;
                    $order_id = $order->getId() ? (int)$order->getId() : 0;
                    $order_code = $order->getCode() ? $order->getCode() : "";
                    $order_status = $order->getStatus() ? $order->getStatus() : "";
                    $problems = "Đơn hàng đã mua lớn hơn 5 ngày không có mã vận đơn";
                    $time = "";
                    if($order->getBoughtTime()){
                        $time = date('d/m/Y', strtotime($order->getBoughtTime()));
                    }
                    $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                    ?>
                    <tr>
                        <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                        <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                        <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                        <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                        <td width="40%" style="text-align: left; padding: 5px;">
                            <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>

        </tbody>
    </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã mua lớn hơn 7 ngày chưa chuyển trạng thái 'Nhận hàng từ người bán' (<?php echo sizeof($data['order3']); ?>)</h3>
    <?php if(sizeof($data['order3']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
                <?php $count = 0; ?>
                <?php foreach($data['order3'] as $order){ ?>
                    <?php if($order instanceof \Order){ ?>
                        <?php
                        $count++;
                        $order_id = $order->getId() ? (int)$order->getId() : 0;
                        $order_code = $order->getCode() ? $order->getCode() : "";
                        $order_status = $order->getStatus() ? $order->getStatus() : "";
                        $time = "";
                        if($order->getBoughtTime()){
                            $time = date('d/m/Y', strtotime($order->getBoughtTime()));
                        }
                        $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                        ?>
                        <tr>
                            <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                            <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                            <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                            <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                            <td width="40%" style="text-align: left; padding: 5px;">
                                <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>

            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã "Nhận hàng từ người bán", không kiểm sau 1 ngày chưa thấy xuất kho tiếp nhận. (Chuyển trạng thái "Vận chuyển") (<?php echo sizeof($data['order4']); ?>)</h3>
    <?php if(sizeof($data['order4']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
                <?php $count = 0; ?>
                <?php foreach($data['order4'] as $order){ ?>
                    <?php if($order instanceof \Order){ ?>
                        <?php
                        $count++;
                        $order_id = $order->getId() ? (int)$order->getId() : 0;
                        $order_code = $order->getCode() ? $order->getCode() : "";
                        $order_status = $order->getStatus() ? $order->getStatus() : "";
                        $time = "";
                        if($order->getReceivedFromSellerTime()){
                            $time = date('d/m/Y', strtotime($order->getReceivedFromSellerTime()));
                        }
                        $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                        ?>
                        <tr>
                            <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                            <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                            <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                            <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                            <td width="40%" style="text-align: left; padding: 5px;">
                                <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>

            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã "Nhận hàng từ người bán", có kiểm sau 3 ngày chưa thấy xuất kho tiếp nhận (chuyển trạng thái "Vận chuyển") (<?php echo sizeof($data['order5']); ?>)</h3>
    <?php if(sizeof($data['order5']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
            <?php $count = 0; ?>
            <?php foreach($data['order5'] as $order){ ?>
                <?php if($order instanceof \Order){ ?>
                    <?php
                    $count++;
                    $order_id = $order->getId() ? (int)$order->getId() : 0;
                    $order_code = $order->getCode() ? $order->getCode() : "";
                    $order_status = $order->getStatus() ? $order->getStatus() : "";
                    $time = "";
                    if($order->getReceivedFromSellerTime()){
                        $time = date('d/m/Y', strtotime($order->getReceivedFromSellerTime()));
                    }
                    $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                    ?>
                    <tr>
                        <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                        <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                        <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                        <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                        <td width="40%" style="text-align: left; padding: 5px;">
                            <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>

            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng chuyển phát nhanh đã "Nhận hàng từ người bán", chưa thấy xuất kho tiếp nhận (chuyển trạng thái "Vận chuyển") (<?php echo sizeof($data['order6']); ?>)</h3>
    <?php if(sizeof($data['order6']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
            <?php $count = 0; ?>
            <?php foreach($data['order6'] as $order){ ?>
                <?php if($order instanceof \Order){ ?>
                    <?php
                    $count++;
                    $order_id = $order->getId() ? (int)$order->getId() : 0;
                    $order_code = $order->getCode() ? $order->getCode() : "";
                    $order_status = $order->getStatus() ? $order->getStatus() : "";
                    $time = "";
                    if($order->getReceivedFromSellerTime()){
                        $time = date('d/m/Y', strtotime($order->getReceivedFromSellerTime()));
                    }
                    $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                    ?>
                    <tr>
                        <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                        <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                        <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                        <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                        <td width="40%" style="text-align: left; padding: 5px;">
                            <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>

            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng chuyển phát nhanh đã chuyển trạng thái "Vận chuyển", sau 3 ngày chưa thấy nhập kho HN (<?php echo sizeof($data['order7']); ?>)</h3>
    <?php if(sizeof($data['order7']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
            <?php $count = 0; ?>
            <?php foreach($data['order7'] as $order){ ?>
                <?php
                $count++;
                $order_id = $order->getId() ? (int)$order->getId() : 0;
                $order_code = $order->getCode() ? $order->getCode() : "";
                $order_status = $order->getStatus() ? $order->getStatus() : "";
                $time = "";
                if($order->getTransportingTime()){
                    $time = date('d/m/Y', strtotime($order->getTransportingTime()));
                }
                $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                ?>
                <tr>
                    <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                    <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                    <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                    <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                    <td width="40%" style="text-align: left; padding: 5px;">
                        <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                    </td>
                </tr>
            <?php } ?>

            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã chuyển trạng thái "Vận chuyển", sau 4 ngày chưa thấy nhập kho HCM (<?php echo sizeof($data['order8']); ?>)</h3>
    <?php if(sizeof($data['order8']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th>STT</th>
                <th>Mã đơn hàng</th>
                <th>Trạng thái</th>
                <th>Thời gian mua hàng</th>
                <th>Link đơn hàng</th>
            </tr>
            </thead>
            <tbody>
            <?php $count = 0; ?>
            <?php foreach($data['order8'] as $order){ ?>
                <?php
                $count++;
                $order_id = $order->getId() ? (int)$order->getId() : 0;
                $order_code = $order->getCode() ? $order->getCode() : "";
                $order_status = $order->getStatus() ? $order->getStatus() : "";
                $problems = 'Đơn hàng đã chuyển trạng thái "Vận chuyển", sau 4 ngày chưa thấy nhập kho HCM';
                $time = "";
                if($order->getTransportingTime()){
                    $time = date('d/m/Y', strtotime($order->getTransportingTime()));
                }
                $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
                ?>
                <tr>
                    <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                    <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                    <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                    <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                    <td width="40%" style="text-align: left; padding: 5px;">
                        <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                    </td>
                </tr>
            <?php } ?>

            </tbody>
        </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã chuyển trạng thái "Vận chuyển", sau 7 ngày chưa thấy nhập kho HN (<?php echo sizeof($data['order9']); ?>)</h3>
    <?php if(sizeof($data['order9']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
        <thead>
        <tr>
            <th>STT</th>
            <th>Mã đơn hàng</th>
            <th>Trạng thái</th>
            <th>Thời gian mua hàng</th>
            <th>Link đơn hàng</th>
        </tr>
        </thead>
        <tbody>
        <?php $count = 0; ?>
        <?php foreach($data['order9'] as $order){ ?>
            <?php
            $count++;
            $order_id = $order->getId() ? (int)$order->getId() : 0;
            $order_code = $order->getCode() ? $order->getCode() : "";
            $order_status = $order->getStatus() ? $order->getStatus() : "";
            $problems = 'Đơn hàng đã chuyển trạng thái "Vận chuyển", sau 7 ngày chưa thấy nhập kho HN';
            $time = "";
            if($order->getTransportingTime()){
                $time = date('d/m/Y', strtotime($order->getTransportingTime()));
            }
            $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
            ?>
            <tr>
                <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                <td width="40%" style="text-align: left; padding: 5px;">
                    <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng đã chuyển trạng thái "Vận chuyển", sau 10 ngày chưa thấy nhập kho HCM. (<?php echo sizeof($data['order10']); ?>)</h3>
    <?php if(sizeof($data['order10']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
        <thead>
        <tr>
            <th>STT</th>
            <th>Mã đơn hàng</th>
            <th>Trạng thái</th>
            <th>Thời gian mua hàng</th>
            <th>Link đơn hàng</th>
        </tr>
        </thead>
        <tbody>
        <?php $count = 0; ?>
        <?php foreach($data['order10'] as $order){ ?>
            <?php
            $count++;
            $order_id = $order->getId() ? (int)$order->getId() : 0;
            $order_code = $order->getCode() ? $order->getCode() : "";
            $order_status = $order->getStatus() ? $order->getStatus() : "";
            $problems = 'Đơn hàng đã chuyển trạng thái "Vận chuyển", sau 10 ngày chưa thấy nhập kho HCM.';
            $time = "";
            if($order->getTransportingTime()){
                $time = date('d/m/Y', strtotime($order->getTransportingTime()));
            }
            $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
            ?>
            <tr>
                <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                <td width="40%" style="text-align: left; padding: 5px;">
                    <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng ở trạng thái "Chờ giao", sau 10 ngày vẫn chưa thấy chuyển trạng thái "Yêu cầu giao" (<?php echo sizeof($data['order11']); ?>)</h3>
    <?php if(sizeof($data['order11']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
        <thead>
        <tr>
            <th>STT</th>
            <th>Mã đơn hàng</th>
            <th>Trạng thái</th>
            <th>Thời gian mua hàng</th>
            <th>Link đơn hàng</th>
        </tr>
        </thead>
        <tbody>
        <?php $count = 0; ?>
        <?php foreach($data['order11'] as $order){ ?>
            <?php
            $count++;
            $order_id = $order->getId() ? (int)$order->getId() : 0;
            $order_code = $order->getCode() ? $order->getCode() : "";
            $order_status = $order->getStatus() ? $order->getStatus() : "";
            $problems = 'Đơn hàng ở trạng thái "Chờ giao", sau 10 ngày vẫn chưa thấy chuyển trạng thái "Yêu cầu giao"';
            $time = "";
            if($order->getWaitingDeliveryTime()){
                $time = date('d/m/Y', strtotime($order->getWaitingDeliveryTime()));
            }
            $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
            ?>
            <tr>
                <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                <td width="40%" style="text-align: left; padding: 5px;">
                    <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

    <h3 style="padding-top: 10px;">Đơn hàng ở trạng thái "Yêu cầu giao", hơn 10 ngày chưa thấy chuyển trạng thái "Đang giao" (<?php echo sizeof($data['order12']); ?>)</h3>
    <?php if(sizeof($data['order12']) > 0){ ?>
        <table border="1" style="width: 80%;" cellspacing="0" cellpadding="0">
        <thead>
        <tr>
            <th>STT</th>
            <th>Mã đơn hàng</th>
            <th>Trạng thái</th>
            <th>Thời gian mua hàng</th>
            <th>Link đơn hàng</th>
        </tr>
        </thead>
        <tbody>
        <?php $count = 0; ?>
        <?php foreach($data['order12'] as $order){ ?>
            <?php
            $count++;
            $order_id = $order->getId() ? (int)$order->getId() : 0;
            $order_code = $order->getCode() ? $order->getCode() : "";
            $order_status = $order->getStatus() ? $order->getStatus() : "";
            $problems = 'Đơn hàng ở trạng thái "Yêu cầu giao", hơn 10 ngày chưa thấy chuyển trạng thái "Đang giao"';
            $time = "";
            if($order->getConfirmDeliveryTime()){
                $time = date('d/m/Y', strtotime($order->getConfirmDeliveryTime()));
            }
            $link_order = "http://seudo.vn/backend/order/detail/" . $order_id;
            ?>
            <tr>
                <td width="5%" style="text-align: center; padding: 5px;"><?php echo $count; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $order_code ?></td>
                <td width="15%" style="text-align: center; padding: 5px;"><?php echo \Order::$statusTitle[$order_status]; ?></td>
                <td width="20%" style="text-align: center; padding: 5px;"><?php echo $time ?></td>
                <td width="40%" style="text-align: left; padding: 5px;">
                    <a target="_blank" href="<?php echo $link_order ?>" title="<?php echo $order_code ?>"><?php echo $link_order ?></a>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>
    <?php }else{ ?>
        <div style="text-align: center">Không có đơn hàng nào!</div>
    <?php } ?>

</center>