<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html lang="vi">
<body  style="margin:0; padding: 0;">
<table bgcolor="#f1f1f1" width="100%" height="100%" align="center" height="60" style="border-collapse: collapse"  border="0" cellspacing="0" cellpadding="0">
    <tr align="center">
        <td valign="top">
            <table bgcolor="#f1f1f1" height="60" style="border-collapse: collapse"  border="0" cellspacing="0" cellpadding="0">
                <tr valign="middle" height="40">
                    <td width="9"></td>
                    <td width="217" valign="middle">
                        <img src="cid:google" border="0" alt="Google Accounts" style="display: block;" height="40">
                    </td>
                    <td  width="327" style="font-size: 13px; font-family: arial, sans-serif; color: #777777; text-align: right">
                        Dương Văn Trường
                    </td>
                    <td width=3D"10"></td>
                    <td><img src="cid:profilephoto" /></td>
                    <td width="10"></td>
                </tr>
            </table>
            <table  border="1" bordercolor="#e5e5e5" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="text-align: left">
                <tr>
                    <td height="15" style="border-top: none; border-bottom: none; border-left: none; border-right: none;">
                    </td>
                </tr>
                <tr>
                    <td width="15" style="border-top: none; border-bottom: none; border-left: none; border-right: none;">
                    </td>
                    <td width="568" valign="top" style="font-size: 83%; border-top: none; border-bottom: none; border-left: none; border-right: none; font-size: 13px; font-family: arial, sans-serif; color: #222222; line-height:18px">
                        Xin chào namtuocdent90,
                        <br />
                        <br />
                        Số điện thoại khôi phục cho tài khoản Google của bạn - namtuocdent90@gmail.com - đã được thay đổi gần đây. Nếu bạn đã thực hiện thay đổi này, bạn không cần phải làm gì nữa.
                        <br />
                        <br />
                        Nếu bạn không thay đổi điện thoại khôi phục của mình, một người nào đó có thể đã xâm nhập vào tài khoản của bạn. Hãy truy cập liên kết sau để biết thêm thông tin:
                        <a href="https://support.google.com/accounts/bin/answer.py?answer=3D2450236" style="text-decoration: none; color: #4D90FE">https://support.google.com/accounts/bin/answer.py?answer=2450236.</a>
                        <br />
                        <br />
                        Nếu bạn gặp sự cố khi truy cập tài khoản của mình, đặt lại mật khẩu của bạn bằng cách nhấp vào nút bên dưới:
                        <br />
                        <br />
                        <a href="https://accounts.google.com/RecoverAccount?fpOnly=1&amp;source=ancrpse&amp;Email=duongthiloidk@gmail.com" target="_blank" style="text-align: center; font-size: 11px; font-family: arial, sans-serif; color:white; font-weight: bold; border-color: #3079ed; background-color: #4d90fe; background-image: linear-gradient(top,#4d90fe,#4787ed); text-decoration:none; display:inline-block; height: 27px; padding-left: 8px; padding-right:8px; line-height: 27px; border-radius: 2px; border-width: 1px;">
        <span style="color: white;">
        Đặt lại mật khẩu
        </span>
                        </a>
                        <br />
                        <br />
                        Trân trọng,
                        <br />Nhóm tài khoản Google ,
                    </td>
                    <td width="15" style="border-top: none; border-bottom:none; border-left: none; border-right: none;">
                    </td>
                </tr>
                <tr>
                    <td height="15" style="border-top: none; border-bottom:none; border-left: none; border-right: none;">
                    </td>
                </tr>
                <tr>
                    <td width="15" style="border-top: none; border-bottom:none; border-left: none; border-right: none;"></td>
                    <td width="568" style="font-size: 11px; font-family: arial, sans-serif; color: #777777; border-top: none; border-bottom: none; border-left: none; border-right: none;">
                        Email này không thể nhận được thư trả lời. Để biết thêm thông tin, truy cập vào <a href="https://support.google.com/accounts/bin/answer.py?answer=3D2450236" style="text-decoration: none; color: #4D90FE"><span style="color: #4D90FE;">Trung tâm trợ giúp của tài khoản Google. </span></a>
                    </td>
                    <td width="15" style="border-top: none; border-bottom:none; border-left: none; border-right: none;"></td>
                </tr>
                <tr>
                    <td height="15" style="border-top: none; border-bottom: none; border-left: none; border-right: none;">
                    </td>
                </tr>
                <tr>
                    <td width="15" style="border-top: none; border-bottom: none; border-left: none; border-right: none;"></td>

                    <td width="568" style="font-size: 11px; font-family: arial, sans-serif; color: #777777; border-top: none; border-bottom: none;border-left: none; border-right: none;">
                        Nếu namtuocdent90@gmail.com không phải là tài khoản Google của bạn,
                        <a href="https://accounts.google.com/AccountDisavow?adt=3DAOX8kioJ5a__TSeEpOaV76zch7xwhZyb-7CBcFoaVlrYDgoaPo-LsBmr9sUpKhs9ZUt4Pw" target="_blank">
                            nhấp vào đây
                        </a>  để ngắt kết nối địa chỉ email của bạn khỏi tài khoản này.
                    </td>
                    <td width="15" style="border-top: none; border-bottom: none; border-left: none; border-right: none;"></td>
                </tr>
                <tr>
                    <td height="15" style="border-top: none; border-bottom:none; border-left: none; border-right: none;">
                    </td>
                </tr>
            </table>
            <table  bgcolor="#f1f1f1" height="80" style="text-align:left">
                <tr valign="middle">

                    <td style="font-size: 11px; font-family: arial, sans-serif; color: #777777;">
                        Bạn đã nhận thông báo dịch vụ qua email bắt buộc này để cập nhật về những thay đổi quan trọng cho sản phẩm hoặc tài khoản Google của bạn.
                        <br />
                        <br />
                        <div  style="direction: ltr;">
                            &copy; 2014 Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>