<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 5/14/14
 * Time: 5:09 PM
 */
echo $notify_data;
?>
<h4>Kính gửi Quý khách hàng thân thiết!</h4>
<p>Tình hình căng thẳng chính trị tại biển Đông trong thời gian qua đã gây ảnh hưởng không nhỏ tới các hoạt động giao thương giữa Việt Nam và Trung Quốc. Đó cũng chính là lý do dẫn tới việc hàng hóa Quý khách đặt mua đã được kiểm kê, đóng gói nhưng chưa thể thông quan, chuyển về theo đúng lịch trình thông thường…</p>

<p>Mặc dù đây là nguyên nhân khách quan, bất khả kháng, nằm ngoài tầm kiểm soát và trách nhiệm; nhưng trong khả năng của mình, chúng tôi sẽ nỗ lực hết sức trong việc tìm kiếm biện pháp để cải thiện tình hình.</p>
<p>Kính mong Quý khách thấu hiểu và tiếp tục đồng hành cùng chúng tôi vượt qua giai đoạn khó khăn này.</p>
<p>Trân trọng!</p>
<p>Ban Quản trị website</p>
