<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: none !important; height: 100% !important; font-family:arial; width: 100% !important; min-width: 100% !important; background-color: #dddddd; margin: 0; padding: 0;";>
<left>
    <div style="padding: 10px; text-align: left; background: transparent;">
        <p style="padding-left: 30px;"><b>Kính gửi</b>: Quý khách hàng thân thiết!</p>
        <p style="padding-left: 30px;">Thấu hiểu được tầm quan trọng và những ảnh hưởng của thời gian lưu thông hàng hóa đối với  cơ hội kinh doanh của Quý khách, Công ty CP Truyền Thông và Công Nghệ Alimama (đơn vị chủ quản website: <a style="color: blue" href="www.orderhang.com" target="_blank">www.orderhang.com</a>/<a style="color: blue" target="_blank" href="www.seudo.vn">www.seudo.vn</a>) khai trương gói dịch vụ <b>Chuyển phát nhanh Siêu tốc (Trung Quốc - Việt Nam)</b>.</p>

        <h3 style="text-decoration: underline; padding-top: 10px">Uư thế của dịch vụ:</h3>
        <ul>
            <li>
                Phí dịch vụ cạnh tranh, nhiều ưu đãi, trọng lượng tính phí chính xác đến 100g
            </li>
            <li>
                Thời gian vận chuyển, lưu thông hàng hóa nhanh gấp 2 so với thời gian vận chuyển thông thường. Thời gian chỉ từ 2 – 3 ngày về đến Hà Nội và 2 – 4 ngày về đến TP. Hồ Chí Minh
            </li>
            <li>
                Giảm tới mức tối đa những hạn chế, phụ thuộc của thị trường
            </li>
            <li>
                Bảo vệ hàng hóa chuyên nghiệp khi vận chuyển
            </li>
            <li>
                Rút ngắn thời gian nhập hàng - Tăng cơ hội kinh doanh
            </li>
            <li>
                Tiện ích thông báo hàng về kho tự động từ Orderhang.com/Seudo.vn

            </li>
        </ul>

        <p style="padding-left: 30px">Nhân dịp khai trương dịch vụ, chúng tôi trân trọng gửi tới Quý khách Chương trình Ưu đãi vô cùng hấp dẫn <b>“Chuyển phát nhanh - Ưu đãi shock”.</b></p>
        <p style="padding-left: 30px">
            Theo đó, khi đặt đơn hàng dù chỉ 1kg, khách hàng sẽ hưởng mức đơn giá như khi đặt 100kg. Chúng tôi hy vọng, chương trình sẽ mang tới cho Quý khách nhiều lợi ích thiết thực và khắc phục được những khó khăn về lưu thông hàng hóa trong thời kỳ giao thương khó khăn này.
        </p>

        <div style="padding: 10px 0; text-align: center">
            <img src="http://seudo.vn/assets/images/templates/email/chuyen-phat-nhanh-624x299.jpg" alt="" />
        </div>

        <p>
            Chi tiết và cách tính phí Chuyển phát nhanh Siêu tốc (Trung Quốc – Việt Nam), Quý khách hàng xem thêm <a target="_blank" href="http://hotro.seudo.vn/dichvuchuyenphatnhanh/">tại đây</a>  (<a href="http://hotro.seudo.vn/dichvuchuyenphatnhanh/" target="_blank">http://hotro.seudo.vn/dichvuchuyenphatnhanh/</a>)
        </p>

        <p>Mọi thắc mắc liên quan đến dịch vụ, Quý khách vui lòng liên hệ số điện thoại: 096 242 5175 hoặc chat với CSKH của chúng tôi để được hỗ trợ. </p>
    </div>

</left>
</body>