<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<div width="650" border="0" style="margin:auto;border-radius:3px; background-color:white; font-family:Arial, Helvetica, sans-serif;font-size:14px">
    <span style="font-size:18px;font-family:Arial, Helvetica, sans-serif;">
        Chào <span style="font-weight:bold">
               <?php echo $fullname ?>!
             </span>
    </span>
    <br><br>
    Cảm ơn bạn đã sử dụng dịch vụ của Sếu Đỏ.<br><br>
    Tài khoản <strong><?php echo $username ?></strong> của bạn đã được đăng ký thành công.<br><br>
    Để bắt đầu sử dụng dịch vụ, xin vui lòng xem
    <a href="<?php echo $link ?>">hướng dẫn đặt hàng.</a>
    <br><br>Ngoài ra bạn có thể:<br>
    - <a href="<?php echo $link ?>user/nap-tien">Nạp tiền để bắt đầu mua hàng.</a><br>
    - <a href="<?php echo $link ?>user/thong-tin">Bổ sung thông tin cá nhân.</a><br>
    - <a href="<?php echo $link ?>user/dia-chi-nhan-hang">Tạo và quản lý địa chỉ nhận hàng.</a><br>
    <br>
    Mọi thắc mắc xin liên hệ với Chăm Sóc Khách Hàng của chúng tôi:<br>
    - Email: cskh@seudo.vn<br>
    - Hotline: <b>04 629 335 36</b><br>
    Hoặc sử dụng công cụ chat trực tuyến trên trang.<br><br>
    Chúc công việc kinh doanh của quý khách gặp nhiều thuận lợi. Xin cảm ơn! <br><br><br>
    Thân mến,<br><br>
    <span style="margin:auto;color:#747474;line-height:30px;font-size:11px;font-family:Arial, Helvetica, sans-serif;">(c) 2013, Sếu Đỏ Việt Nam. All right reserved</span></br></br>
    <span style="margin:auto; font-size:11px; color:#33a0e8;font-family:Arial, Helvetica, sans-serif;"><a href="<?php echo $link ?>" style="color:#33a0e8">http://seudo.vn</a></span>
</div>