<!-- Begin header -->
<section class="page-register register login" style="margin-top: 20px;">
    <nav class="container" >
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <p style="font-size: 18px;text-align: center;">
                    <span style="color: rgb(177, 0, 0); font-size: 40px;">Seudo.vn</span>
                    .Vui lòng đăng nhập để đặt hàng
                </p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">
                <div class="seu-module">
                    <div class="module-inner">
                        <div class="module-title">
                            <p class="title"><span class="title-page">Đăng nhập</span></p>
                        </div>
                        <div class="module-ct">
                            <form role="form" method="POST" class="fr-login" name="fr-login" id="_frm-login">
                                <div class="module-ct-item">
                                    <div class="left-ct">
                                        <span class="normal-blod">Tài khoản:</span><span class="red-normal">*</span>
                                    </div>
                                    <div class="right-ct pull-right">
                                        <p class="red-normal re-error err-cred err-ajax"></p>
                                        <input name="credential" id="exampleInput" class="form-control form-myinput" type="text" placeholder="Tài khoản hoặc email đã kích hoat" >
                                        <p class="normal">Sử dụng các ký tự latin (a-z) và ký tự gạch dưới. Từ 3 đến 15 ký tự</p>
                                    </div>
                                </div>

                                <div class="module-ct-item password">
                                    <div class="left-ct">
                                        <span class="normal-blod">Mật khẩu:</span><span class="red-normal">*</span>
                                    </div>
                                    <div class="right-ct pull-right">
                                        <p class="red-normal re-error err-pass"></p>
                                        <input name="password" id="exampleInput" class="form-control form-myinput" type="password" placeholder="Mật khẩu (tối thiểu 6 ký tự)" >


                                    </div>
                                    <div class="regis-item made">
                                        <p class="normal"><label>
                                                <input type="checkbox" class="login-checkbox" id="remember" name="remember" checked="true">
                                                Ghi nhớ đăng nhập
                                            </label>
                                        </p>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-3"></div>
                                        <div class="col-xs-6">
                                            <p class="page-login submit">
                                                <button id="_bt-login" class="btn btn-blue btn-lg btn-login" type="submit">Đăng nhập</button>
                                            </p>
                                        </div>
                                    </div>

                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </nav>
</section>

<!-- End header -->
<style type="text/css">
    .page-register.register.login p.page-login.submit { width: 100%; }
</style>
