<div class="profile-user">
    <div class="sidebar-user-header">
        <p class="title">SeuDo</p>

        <p class="normal">Con Sếu Đỏ</p>
    </div>
    <div class="avatar">
        <img src="images/imgdemo/avatardefault.png">
    </div>
    <div class="item-sidebar-menu">
        <div class="menu-title">
            <p class="title uppercase">đơn hàng</p>
        </div>
        <ul class="sidebar-user">
            <li>
                <a href="#">+ Chờ thanh toán<span class="count">50</span></a>
            </li>
            <li>
                <a href="#">+ Đang hoạt động<span class="count">99+</span></a>
            </li>
            <li class="active">
                <a href="#">+ Kết thúc</a>
            </li>
            <li>
                <a href="#">+ Hết hàng / Hủy</a>
            </li>
            <li>
                <a href="#">+ Đang khiếu nại</a>
            </li>
        </ul>
    </div>
    <div class="item-sidebar-menu">
        <div class="menu-title">
            <p class="title uppercase">giao dịch</p>
        </div>
        <ul class="sidebar-user">
            <li>
                <a href="#">+ Lịch sử giao dịch</a>
            </li>
            <li>
                <a href="#">+ Nạp tiền</a>
            </li>
            <li>
                <a href="#">+ Rút tiền</a>
            </li>

        </ul>
    </div>
    <div class="item-sidebar-menu">
        <div class="menu-title">
            <p class="title uppercase">lịch sử</p>
        </div>
        <ul class="sidebar-user">
            <li>
                <a href="#">+ Sản phẩm đã mua</a>
            </li>
            <li>
                <a href="#">+ Sản phẩm theo doi</a>
            </li>
            <li>
                <a href="#">+ Người bán quan tâm</a>
            </li>

        </ul>
    </div>
    <div class="item-sidebar-menu">
        <div class="menu-title">
            <p class="title uppercase">cá nhân</p>
        </div>
        <ul class="sidebar-user">
            <li>
                <a href="#">+ Thông tin</a>
            </li>
            <li>
                <a href="#">+ Đổi mật khẩu</a>
            </li>
            <li>
                <a href="#">+ Thoát</a>
            </li>

        </ul>
    </div>
</div>