<?php
use Flywheel\Document\Html;
/** @var Html $document */
$document = $this->document();
?>
<!DOCTYPE html>
<html>
<head>
    <base href="<?php echo $document->getBaseUrl() ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo $document->title ;?></title>
    <?php echo $document->css(); ?>
    <?php echo $document->js('TOP'); ?>

</head>
<body>

<div id="main-content">
    <?php echo $buffer ?>
</div>

</body>
<?php echo $document->js('BOTTOM'); ?>
</html>