<?php
/** @var \Flywheel\View\Render $this */
/** @var \Flywheel\Document\Html $document */
$document = $this->document();
$document->title = t("Quên mật khẩu");
$document->addCss($document->getPublicPath() .'user/assets_v2/css/email.css');
$submit_error = @$submit_error;
?>
<section class="cart-header introbook">
    <nav class="container" >
        <div class="page-email">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8 small-centered email-confirmation">
                    <nav class="container" >
                        <div class="page-email">
                            <div class="row">
                                <div class="col-md-2"></div>
                                <div class="col-md-6 small-centered email-confirmation">
                                    <h2 class="h2">Nhập mật khẩu mới.</h2>
                                    <form name="reset_password" method="post" action="">
                                        <p>Hệ thống đã xác nhận yêu cầu của bạn</p>
                                        <?php if (isset($submit_error['common'])) :?>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="re-error" style="color:red">
                                                        <?php echo $submit_error['common']; ?>
                                                    </p>
                                                </div>
                                            </div><br>
                                        <?php endif; ?>

                                        <p>Nhập mật khẩu mới</p>
                                        <div class="row">
                                            <div class="col-md-7">
                                                <input class="form-control form-myinput" type="password" name="new_pass" placeholder="Từ 6 ký tự trở lên.">
                                            </div>
                                            <div class="col-md-5">
                                                <?php if(isset($submit_error['new_pass'])) :?>
                                                    <p class="re-error" style="color:red"><?php echo $submit_error['new_pass']; ?></p>
                                                <?php else : ?>
                                                    &nbsp;
                                                <?php endif; ?>
                                            </div>
                                        </div><br>
                                        <p>Nhập lại mật khẩu mới</p>
                                        <div class="row">
                                            <div class="col-md-7">
                                                <input class="form-control form-myinput" type="password" name="confirm_pass" placeholder="Từ 6 ký tự trở lên.">
                                            </div>
                                            <div class="col-md-5">
                                                <p class="re-error inline" style="color:red">
                                                    <?php if(isset($submit_error['confirm_pass'])) :?>
                                                <p class="re-error" style="color:red"><?php echo $submit_error['confirm_pass']; ?></p>
                                                <?php else : ?>
                                                    &nbsp;
                                                <?php endif; ?>
                                                </p>
                                            </div>
                                        </div><br>
                                        <input name="_csrf" value="<?php echo $this->request()->getCsrfToken() ;?>" type="hidden">
                                        <button class="btn btn-blue btn">Tạo mật khẩu</button>
                                    </form>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                    </nav>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </nav>