<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 1/2/14
 * Time: 11:56 AM
 */
$document = $this->document();
$publicPath = $document->getPublicPath();
$cssPath = $publicPath . 'assets/css/';
$jsPath = $publicPath . 'assets/js/process/';
$jsPathFront = $publicPath . 'assets/js/';
$profile_fb = @$profile_fb;
$user_check = @$user_check;
?>
<script>
    $(document).ready(function(){
        $('#passwordConfirm').bind('keypress', function(e) {
            if(e.keyCode==13){
                $('div.loading-face').show();
                var password = $('#passwordConfirm').val();
                UserFacebook.confirmPassword(password);
            }
        });
    });

</script>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-4 col-sm-4 col-md-4">
                    <div class="avatar">
                        <img src="<?php echo $profile_fb['avatar'] ?>" />
                    </div>
                    <p class="normal icon-facebook">
                        <span class="arow"></span><?php echo $profile_fb['first_name'].' ' ?><?php echo $profile_fb['last_name'] ?>
                    </p>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <form action="#">
                        <div class="regis-item">
                            <p class="normal-blod">Chúng tôi tìm thấy địa chỉ Email của bạn trên hệ thống sếu đỏ.</p>
                            <p class="normal">Hãy xác nhận mật khẩu để kết nối (<span style="font-size: 11px">Bạn chỉ thực hiện điều này 1 lần</span>)</p>
                        </div>
                        <div class="regis-item regis-item-avatar"
                             <?php if(!isset($profile_fb['avatar_seudo'])){ ?>style="padding-left:0px" <?php } ?>>
                            <?php if(isset($profile_fb['avatar_seudo'])){ ?>
                            <div class="item-avatar">
                                <img src="<?php echo $profile_fb['avatar_seudo'] ?>" />
                            </div>
                            <?php } ?>
                            <p class="normal text">
                                <?php echo $user_check->username ?>
                            </p>
                            <p class="normal">
                                <input id="passwordConfirm" class="form-control form-myinput pull-left"
                                                     type="password" placeholder="Mật khẩu đăng nhập..." >
                            <p class="red-normal _error _errorPassword" style="display: none"></p>
                            </p>
                        </div>



                        <p class="normal submitfacebook">
                            <button class="btn btn-blue" id="btnConfirmPassFacebook" type="button">Đăng nhập và kết nối</button></p>
                    </form>
                </div>
            </div>
        </div>

        <div class="loading-face" data-box="login" style="display: none">
            <div id="facebookG">
                <div id="blockG_1" class="facebook_blockG">
                </div>
                <div id="blockG_2" class="facebook_blockG">
                </div>
                <div id="blockG_3" class="facebook_blockG">
                </div>
            </div>
        </div>
    </div><!-- /.modal-content -->
</div>