<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 1/2/14
 * Time: 10:06 AM
 */
$document = $this->document();
$publicPath = $document->getPublicPath();
$link_facebook = \SeuDo\Main::getHomeRouter()->createUrl('ConnectFacebook/connect_facebook');
?>
<div>
    <h3>Bạn đã đăng ký thành công với tài khoản : <strong>admin</strong>. Vui lòng khởi tạo mật khẩu để quá trình đăng ký hoàn tất</h3>
Nhập password:
<input type="password" value="" id="password_init" />
<input type="password" value="" id="password_confirm" />
<button id="password_ok" type="button">Xác nhận</button>
</div>