<?php
$document = $this->document();
$publicPath = \SeuDo\Main::getHomeUrl();
$document->title = t("Trang chủ - Sếu đỏ.vn");
?>
<!--<section class="home-note">-->
<!--    <nav class="container">-->
<!--        <div class="row">-->
<!--            <div class="alert alert-alert" style="margin-top: -30px; font-size: 14px; margin-bottom: 30px;">-->
<!--                <h3 style="text-align: center;">Kính gửi Quý khách hàng!</h3>-->
<!--                <p>Theo phong tục tại địa phương, trong các ngày từ 07/09/2014 đến 09/09/2014, phía Người bán tại Trung Quốc có đợt nghỉ Tết Trung thu. Vì vậy, trong khoảng thời gian trên, các công việc liên quan đến mua và vận chuyển hàng hóa có thể sẽ được đáp ứng chậm hơn thời gian thông thường.-->
<!---->
<!---->
<!--                    </p>-->
<!---->
<!--                <p>Trân trọng cảm ơn!</p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </nav>-->
<!--</section>-->
<section class="home-slide">
    <nav class="container" >
        <div class="row">
            <div id="home-slideheader" class="owl-carousel">
                <div class="item">
                    <a href="<?php echo \SeuDo\Main::getHomeUrl() . '/ung-dung' ?>">
                        <img class="lazyOwl" src="<?php echo $publicPath;?>assets/images/banner/CongCuDatHang.jpg"
                             alt="Công cụ đặt hàng">
                    </a>
                </div>
                <div class="item"><img class="lazyOwl" src="<?php echo $publicPath;?>assets/images/imgdemo/1_Nguonhangphongphu.jpg" alt="Nguồn hàng phong phú"></div>
                <div class="item"><img class="lazyOwl" src="<?php echo $publicPath;?>assets/images/banner/de_dang_quan_ly_don_hang.jpg" alt="Dễ dàng quản lý đơn hàng"></div>
                <div class="item"><img class="lazyOwl" src="<?php echo $publicPath;?>assets/images/imgdemo/3_Dedangtinhphidichvu.jpg" alt="Lazy Owl Image"></div>
                <div class="item"><img class="lazyOwl" src="<?php echo $publicPath;?>assets/images/imgdemo/4_Tichluydiem.jpg" alt="Lazy Owl Image"></div>
                <div class="item"><img class="lazyOwl" src="<?php echo $publicPath;?>assets/images/banner/seudo-1.jpg" alt="Lazy Owl Image"></div>
            </div>
        </div>
    </nav>
</section>
<section class="home-sl1">
    <nav class="container" >
        <div class="row">
            <div class="col-xs-4 sl1">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <p class="title uppercase normal-blod">nguồn hàng</p>
                            <div class="avatar"></div>
                        </div>
                        <div class="module-ct">
                            <p class="m-ct">Hàng trăm ngàn sản phẩm tới từ các website THƯƠNG MẠI ĐIỆN TỬ lớn nhất Trung Quốc</p>
                            <div class="logo">
                                <div class="left">
                                    <span class="taobao"><a href="http://taobao.com/" target="_blank" rel="nofollow">Taobao.com</a></span>
                                    <span class="ali"><a href="http://www.1688.com/" rel="nofollow">1688.com</a></span>
                                </div>
                                <div class="right">
                                    <span class="tmall"><a href="http://www.tmall.com/" target="_blank" rel="nofollow">Tmall.com</a></span>
                                    <span class="eelly"><a href="http://www.eelly.com/" target="_blank" rel="nofollow">Eelly.com</a></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 sl2">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <p class="title uppercase normal-blod">lợi ích</p>
                            <div class="avatar"></div>
                        </div>
                        <div class="module-ct">
                            <div class="module-ct-item ">
                                <span class="left-item normal-blod"><i>1 </i></span>
                                <p class="normal">Tích lũy điểm thành viên hưởng chiết khấu và ưu đãi.</p>
                            </div>
                            <div class="module-ct-item ">
                                <span class="left-item normal-blod"><i>2 </i></span>
                                <p class="normal">Đặt cọc khi đặt hàng. Thanh toán trước khi giao hàng.</p>
                            </div>
                            <div class="module-ct-item ">
                                <span class="left-item normal-blod"><i>3 </i></span>
                                <p class="normal">Giao dịch online, tiết kiệm công sức nhập hàng.</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 sl3">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <p class="title uppercase normal-blod">quản lý</p>
                            <div class="avatar"></div>
                        </div>
                        <div class="module-ct">
                            <div class="module-ct-item ">
                                <span class="left-item normal-blod"><i>1 </i></span>
                                <p class="normal">Quản lý đơn hàng online thuận tiện.</p>
                            </div>
                            <div class="module-ct-item ">
                                <span class="left-item normal-blod"><i>2 </i></span>
                                <p class="normal">Thông báo tình trạng hàng hóa qua email, SMS, Viber.</p>
                            </div>
                            <div class="module-ct-item ">
                                <span class="left-item normal-blod"><i>3 </i></span>
                                <p class="normal">Dễ dàng theo dõi tài chính nhập hàng.</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</section>


<section class="home-sl2">
    <nav class="container" >
        <div class="row">
            <div class="col-lg-offset-2 col-md-offser-2 col-sm-offset-2  col-xs-8 ">
                <div class="sl2-search">
                    <input type="text" placeholder="Nhập link sản phẩm bạn muốn đặt từ taobao.com, 1688.com và eely.com...." class="form-control form-myinput" id="exampleInput">
                    <span class="uppercase normal-blod buy_item">đặt hàng</span>
                </div>
            </div>
        </div>
    </nav>
</section>


<section class="home-sl3">
    <nav class="container" >
        <div class="row">
            <div class="col-xs-3 sl1 ads_banner" data-link="http://www.1688.com/">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <div class="avatar"></div>
                            <div class="module-link">
                                <p class="normal">1688.com(alibaba)</p>
                            </div>
                            <div class="bg">
                                <p class="normal-blod title">1688.com(alibaba)</p>
                                <p class="normal">Website B2B lớn nhất thế giới</p>
                            </div>
                            <a href="#"></a>
                        </div>
                        <div class="module-ct">

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3 sl2 ads_banner"  data-link="http://taobao.com">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <div class="avatar"></div>
                            <div class="module-link">
                                <p class="normal">Taobao.com</p>
                            </div>
                            <div class="bg">
                                <p class="normal-blod title">Taobao.com</p>
                                <p class="normal">Website bán lẻ lớn nhất Trung Quốc</p>
                            </div>
                            <a href="#"></a>
                        </div>
                        <div class="module-ct">

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3 sl3 ads_banner" data-link="http://www.tmall.com/">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <div class="avatar"></div>
                            <div class="module-link">
                                <p class="normal">Tmall.com</p>
                            </div>
                            <div class="bg">
                                <p class="normal-blod title">Tmall.com</p>
                                <p class="normal">Website bán lẻ hàng hiệu uy tín nhất Trung Quốc</p>
                            </div>
                            <a href="#"></a>
                        </div>
                        <div class="module-ct">

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3 sl4 ads_banner" data-link="http://www.eelly.com/">
                <div class="seu-module ">
                    <div class="module-inner">
                        <div class="module-title">
                            <div class="avatar"></div>
                            <div class="module-link">
                                <p class="normal">eelly.com</p>
                            </div>
                            <div class="bg">
                                <p class="normal-blod title">Eelly.com</p>
                                <p class="normal">Chuyên trang bán buôn hàng thời trang</p>
                            </div>
                            <a href="#"></a>
                        </div>
                        <div class="module-ct">

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </nav>
</section>

<section class="home-sl4 v2">
    <nav class="container">
        <div class="row">
            <?php $this->widget('global.widget.FeeTool'); ?>
        </div>
    </nav>
</section>


<!--    end list cart-->
<!-- conten menu top    -->
<div style="display: none;" class="modal fade" id="myModaldeleteitem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Xóa sản phẩm</h4>
            </div>
            <div class="modal-body">
                <p class="price-red1">Bạn có chắc chắn muốn xóa sản phẩm này</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-gray btn-sm" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-red btn-sm">Yes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>


