<?php
use SeuDo\Main;
$document = $this->document();
$publicPathUser = $document->getPublicPath();
$publicPath = Main::getHomeUrl();
$cssPath = $publicPath . 'assets/css/';
$jsPath = $publicPath . 'assets/js/process/';
$jsPathFront = $publicPath . 'assets/js/';
$document->addCss($publicPathUser . 'assets/css/profile.css');

$document->addJsVar('base_url', Main::getHomeRouter()->createUrl('/'), 'TOP');
$document->addJsVar('LoginFacebookUrl',$publicPath.'ConnectFacebook','TOP');

?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo $document->title != '' ? $document->title : 'Seudo.vn' ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" href="<?php echo $publicPath;?>/assets/images/icon-footer/LogoSeuDo1_ICO.ico">

    <!-- Load JS-->
    <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap-theme.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $publicPath ?>assets/bootstrap/css/bootstrap-select.min.css" rel="stylesheet" type="text/css" media="all">

    <link href="<?php echo $cssPath ?>mytypo.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>header.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>owl.carousel.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $jsPathFront ?>rate/rateit.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>owl.theme.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>cssloading.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath;?>loading.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>style.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>footer.css" rel="stylesheet" type="text/css" media="all">
    <link href="<?php echo $cssPath ?>check-browser.css" rel="stylesheet" type="text/css" media="all">
    <?php echo $document->css(); ?>
    <link href="<?php echo $cssPath ?>responsive.css" rel="stylesheet" type="text/css" media="all">

    <script type="text/javascript" src="<?php echo $jsPathFront;?>jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="<?php echo $publicPath ?>assets/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $publicPath ?>assets/bootstrap/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="<?php echo $jsPathFront ?>rate/jquery.rateit.min.js"></script>
    <script type="text/javascript" src="<?php echo $jsPathFront ?>jqueryui.js"></script>
    <script type="text/javascript" src="<?php echo $jsPathFront . 'jquery.lazyload.js' ?>"></script>
    <script type="text/javascript" src="<?php echo $jsPathFront;?>seudo-frontend.js"></script>
    <script type="text/javascript" src="<?php echo $jsPath;?>order_link_base.js"></script>

    <script type="text/javascript" src="<?php echo $jsPathFront;?>seudo-frontendv2.js"></script>
    <script type="text/javascript" src="<?php echo $publicPathUser;?>assets/js/order_detail.js?t=2"></script>

    <!-- dau's Fuck -->

<!--    --><?php
//    require_once GLOBAL_PATH . '/include/GA.php';
    echo $document->js('TOP');
//    ?>
</head>
<body>
<!-- conten menu top    -->
<div style="display: none;" class="modal fade finish-poup" id="myModaldeleteitem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"><span class="uppercase normal-blod">hoàn thành</span></h4>
            </div>
            <div class="modal-body">
                <p class="normal">Bạn có chắc chắn muốn xóa sản phẩm này ?.</p>
            </div>
            <div class="modal-footer">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">No</button>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <button type="button" class="btn btn-blue">Yes</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<div class="loading-data _loading" style="display: none">
    <div class="content">
        Đang tải dữ liệu <span>...</span>
    </div>
</div>

<span class="remove _alert hidden" data-target="#_alert" data-toggle="modal"></span>

<div style="display: none;" class="modal fade finish-poup" id="_alert" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel"><span class="uppercase normal-blod">Thông báo</span></h4>
            </div>
            <div class="modal-body">
                <p class="price-red1 _message"></p>
            </div>
            <div class="modal-footer">
                <div class="col-lg-6 col-md-6 col-sm-6"  style="margin-left: 25%">
                    <button type="button" class="btn btn-red btn-sm" data-dismiss="modal">Đồng ý</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<!--  Header -->
<?php
$this->widget('app.Widget.Header', array(
    'user' => BaseAuth::getInstance()->getUser(),
    'is_header_slide' => 0
));
?>
<!-- End Header -->

<!-- Main Content -->
<div id="_main_content">
<section class="profile order-acc item-delay-v2">
    <nav class="container">
        <div class="row">
            <div class="profile-body item-delay">
                <?php echo $buffer;?>
            </div>
        </div>
    </nav>
</section>
</div>
<!-- End Content -->

<!-- Footer -->
<?php $this->widget('app.Widget.Footer'); ?>
<!-- End footer -->
</body>

<?php
echo $document->js('BOTTOM-USER');
?>
</html>