<?php
use SeuDo\Main;
use Flywheel\Document\Html;
/** @var Html $document */
$document   = $this->document();
$publicPath = Main::getBackendUrl();
$publicHomePath = Main::getHomeUrl();
$document->addJsVar('backend_url', $controller->createUrl('/'), 'TOP');
?>
<!-- AUI Framework -->
<!DOCTYPE html>
<html>
<head>
    <base href="<?php echo $document->getBaseUrl() ?>">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Login</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Favicons -->

    <link rel="icon" href="assets/images/icon-footer/LogoSeuDo1_ICO.ico">
    <script src="assets/js/jquery-1.10.2.min.js"></script>
    <!--[if lt IE 9]>
    <script src="assets/js/minified/core/html5shiv.min.js"></script>
    <script src="assets/js/minified/core/respond.min.js"></script>
    <![endif]-->
    <!-- Fides Admin CSS Core -->
    <link rel="stylesheet" type="text/css" href="assets/css/aui-production.min.css" />
    <!-- Theme UI -->
    <link id="layout-theme" rel="stylesheet" type="text/css" href="assets/css/dark-blue.min.css" />
    <!-- Fides Admin Responsive -->
    <link rel="stylesheet" type="text/css" href="assets/css/common.min.css" />
    <link rel="stylesheet" type="text/css" href="assets/css/responsive.min.css" />

    <!-- Fides Admin JS -->

    <script type="text/javascript" src="assets/js/process/login.js"></script>

    <script>
        jQuery(window).load(
            function(){

                var wait_loading = window.setTimeout( function(){
                        $('#loading').slideUp('fast');
                        jQuery('body').css('overflow','auto');
                    },1000
                );
            });


    </script>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
<body style="overflow: hidden;">
<input type="hidden" id="backendUrl" value="<?php echo \SeuDo\Main::getBackendUrl();?>">

<div id="loading" class="ui-front loader ui-widget-overlay bg-white opacity-100">
    <img src="assets/images/loader-dark.gif" alt="" />
</div>

<div class="pad20A">
    <?php echo $buffer;?>
</div>



</body>
</html>