<?php
use SeuDo\Main;
use Flywheel\Document\Html;
/** @var Html $document */
$document   = $this->document();
$publicPath = Main::getBackendUrl();
$publicHomePath = Main::getHomeUrl();
$document->addJsVar('backend_url', $controller->createUrl('/'), 'TOP');

?>
<!-- AUI Framework -->
<!DOCTYPE html>
<html>
<head>
    <base href="<?php echo $document->getBaseUrl() ?>">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>In phiếu giao hàng</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="<?php echo $publicPath; ?>assets/js/jquery.printElement.min.js"></script>
    <script src="<?php echo $publicPath; ?>assets/js/process/delivery_print.js"></script>
    <link rel="stylesheet" href="<?php echo $publicPath; ?>assets/css/aui-production.min.css"/>
    <link rel="stylesheet" href="<?php echo $publicPath; ?>assets/css/bootstrap-formhelpers.min.css"/>
    <link rel="stylesheet" href="<?php echo $publicPath; ?>assets/css/style-quanlygiaohang.css"/>
    <link rel="stylesheet" href="<?php echo $publicPath; ?>assets/css/extend/quyen_table.css"/>
    <!-- Favicons -->

    <link rel="icon" href="<?php echo $publicHomePath?>assets/images/icon-footer/LogoSeuDo1_ICO.ico">

<div class="pad20A">
    <?php echo $buffer;?>
</div>



</body>
</html>