<div id="page-title">
    <h3>
        Thêm danh mục
    </h3>
    <div id="breadcrumb-right">

        <div class="float-right"> 
            <a  class="btn medium primary-bg" href="<?php echo $this->createUrl('categories') ?>">&nbsp;<i class="glyph-icon icon-arrow-left"></i> Trở lại&nbsp;</a>

        </div>
    </div>
</div>
<?php
$msg = \Flywheel\Session\Session::getInstance()->getFlash('msg');
if($msg):?>
    <div class="infobox warning-bg"><?php echo $msg?></div>
<?php endif?>
<form method="POST" class="col-md-10 center-margin" action="<?php echo $this->createUrl('categories/add')?>">
    <div class="form-row">
        <div class="form-label col-md-2">
            <label for="">
                Name:
                <span class="required">*</span>
            </label>
        </div>
        <div class="form-input col-md-10">
            <input type="text" class="parsley-validated" data-required="true" data-trigger="change" data-type="text" name="title" id="title" value="<?php echo isset($cat->title)?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-2">
            <label for="">
                Alias:
                <span class="required">*</span>
            </label>
        </div>
        <div class="form-input col-md-10">
            <input type="text" class="parsley-validated" data-required="true" data-trigger="change" data-type="text" name="slug" id="slug" value="<?php echo isset($cat->slug)?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-2">
            <label for="">
                Order:
            </label>
        </div>
        <div class="form-input col-md-10">
            <input type="text" value="0" class="parsley-validated" data-type="number" data-trigger="change" name="order" id="order"  value="<?php echo isset($cat->order)?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-2">
            <label class="label-description" for="">
                Description:
            </label>
        </div>
        <div class="form-input col-md-10">
            <textarea class="parsley-validated" data-rangelength="[10,5000]" data-trigger="keyup" name="description" id="description"> <?php echo isset($cat->description)?></textarea>
        </div>
    </div>
    <div class="divider"></div>
    <div class="form-row">
        <div class="form-input col-md-10 col-md-offset-2">
            <button type="submit"  class="btn medium primary-bg">
                <span class="button-content">
                    Thêm danh mục
                </span>
            </button>
        </div>
    </div>

</form>


<?php
$assets = new \Flywheel\Asset\Asset('backend');
$assets->printTag('./../assets/js/ckeditor/ckeditor.js', 'js');
$assets->printTag('./../assets/js/ckeditor/config.js', 'js');
$assets->printTag('./../assets/js/ckeditor/styles.js', 'js');
?>
<script>
    CKEDITOR.config.height = 300;
    CKEDITOR.config.width = '100%';
    CKEDITOR.replace('description');

</script>