<div id="page-title">
    <h3>
        Danh mục
    </h3>
    <div id="breadcrumb-right">

        <div class="float-right"> 
            <a href="<?php echo $this->createUrl('categories/add') ?>"><i class="glyph-icon icon-plus"></i> Thêm danh mục</a>

        </div>
    </div>
</div>



<table class="table table-striped text-center">
    <thead>
        <tr>
            <th class="text-center">Id</th>
            <th>Name</th>
            <th class="text-center">Slug</th>
            <th class="text-center">Post Count</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($categories AS $cat): ?>
            <tr>
                <td><?php echo $cat->id ?></td>
                <td class="font-bold text-left"><?php echo $cat->title ?></td>
                <td class="font-bold text-left"><?php echo $cat->slug ?></td>
                <td><div class="label bg-orange"><?php echo $cat->post_count ?></div></td>
                <td>
                    <a data-original-title="Edit" href="<?php echo $this->createUrl('categories/edit/'.$cat->id)?>" class="btn small bg-blue-alt tooltip-button" data-placement="top" title="">
                        <i class="glyph-icon icon-edit"></i>
                    </a>
                    <a data-original-title="Remove" class="delete" data-href="<?php echo $this->createUrl('categories/delete/'.$cat->id)?>" class="btn small bg-red tooltip-button" data-placement="top" title="">
                        <i class="glyph-icon icon-remove"></i>
                    </a>

                </td>
            </tr>
        <?php endforeach ?>

    </tbody>
</table>
