<div id="page-title">
    <h3>
        Sửa danh mục <?php echo $category->title?>
    </h3>
    <div id="breadcrumb-right">

        <div class="float-right"> 
            <a href="<?php echo $this->createUrl('categories') ?>"><i class="glyph-icon icon-arrow-left"></i> Trở lại</a>

        </div>
    </div>
</div>

<?php
$msg = \Flywheel\Session\Session::getInstance()->getFlash('msg');
if($msg):?>
    <div class="infobox warning-bg"><?php echo $msg?></div>
<?php endif?>
<form method="POST" class="col-md-10 center-margin" action="<?php echo $this->createUrl('categories/edit/'.$category->id)?>" id="edit-form">
    <div class="form-row">
        <div class="form-label col-md-2">
            <label for="">
                Name:
                <span class="required">*</span>
            </label>
        </div>
        <div class="form-input col-md-10">
            <input type="text" class="parsley-validated" data-required="true" data-trigger="change"  name="title" id="title" value="<?php echo $category->title?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-2">
            <label for="">
                Slug:
                <span class="required">*</span>
            </label>
        </div>
        <div class="form-input col-md-10">
            <input type="text" value="<?php echo $category->slug?>" class="parsley-validated" data-required="true" data-trigger="change"  name="slug" id="slug">
        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-2">
            <label for="">
                Order:
            </label>
        </div>
        <div class="form-input col-md-10">
            <input type="text" value="<?php echo $category->order?>" class="parsley-validated" data-type="number" data-trigger="change" name="order" id="order">
        </div>
    </div>
    <div class="form-row">
        <div class="form-label col-md-2">
            <label class="label-description" for="">
                Description:
            </label>
        </div>
        <div class="form-input col-md-10">
            <textarea class="parsley-validated" data-rangelength="[10,5000]" data-trigger="keyup" name="description" id="description">
                <?php echo $category->description?>
            </textarea>
        </div>
    </div>
    <div class="divider"></div>
    <div class="form-row">
        <input type="hidden" id="superhidden" name="superhidden">
        <div class="form-input col-md-10 col-md-offset-2">
            <button type="submit" class="btn medium primary-bg radius-all-4">Sửa danh mục</button>
        </div>
    </div>

</form>


<?php
$assets = new \Flywheel\Asset\Asset('backend');
$assets->printTag('../../assets/js/ckeditor/ckeditor.js', 'js');
$assets->printTag('../../assets/js/ckeditor/config.js', 'js');
$assets->printTag('../../assets/js/ckeditor/styles.js', 'js');
?>
<script>
    CKEDITOR.config.height = 300;
    CKEDITOR.config.width = '100%';
    CKEDITOR.replace('description');

</script>